import { EquatorHorizonShipClass, FactionShipStats } from "../../types/ships/FactionShipTypes";
import { WeaponMount, WeaponMountSize, WeaponMountPosition, WeaponStatus, WeaponInstance } from "../../types/weapons/WeaponTypes";
import { DamageEffect } from "../../effects/types_effects/WeaponEffects";
import {
  PLASMA_EFFECT,
  GAUSS_EFFECT,
  EXPLOSIVE_EFFECT,
  DAMAGE_BOOST_EFFECT,
  SPEED_BOOST_EFFECT,
  STEALTH_EFFECT,
  SPEED_REDUCTION_EFFECT,
  SHIELD_FIELD_EFFECT,
} from "../../effects/types_effects/shipEffects";

// Special weapon effects for Equator Horizon
const TEMPORAL_EFFECT = {
  type: "damage",
  name: "Temporal Disruption",
  description: "Time-warping energy damage",
  magnitude: 80,
  duration: 3,
  active: true,
  cooldown: 3.0,
  damage: 80,
  damageType: "energy",
  penetration: 0.3,
  strength: 80
} as DamageEffect;

const QUANTUM_EFFECT = {
  type: "damage",
  name: "Quantum Collapse",
  description: "Reality-warping energy damage",
  magnitude: 100,
  duration: 2,
  active: true,
  cooldown: 4.0,
  damage: 100,
  damageType: "energy",
  penetration: 0.4,
  strength: 100
} as DamageEffect;

const HARMONIC_EFFECT = {
  type: "damage",
  name: "Harmonic Resonance",
  description: "Shield-penetrating harmonic damage",
  magnitude: 60,
  duration: 4,
  active: true,
  cooldown: 2.5,
  damage: 60,
  damageType: "energy",
  penetration: 0.25,
  strength: 60
} as DamageEffect;

export const EQUATOR_HORIZON_SHIPS: Record<EquatorHorizonShipClass, FactionShipStats> = {
  celestialArbiter: {
    health: 1500,
    maxHealth: 1500,
    shield: 1000,
    maxShield: 1000,
    energy: 800,
    maxEnergy: 800,
    speed: 80,
    turnRate: 3,
    cargo: 300,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "rail-1",
        size: "large" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "heavy-railgun",
            name: "Heavy Railgun",
            category: "railGun",
            tier: 3,
            baseStats: {
              damage: 300,
              range: 1500,
              accuracy: 0.95,
              rateOfFire: 3,
              energyCost: 15,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: "weapons/railgun/heavy",
            mountRequirements: {
              size: "large" as WeaponMountSize,
              power: 40,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 300,
              range: 1500,
              accuracy: 0.95,
              rateOfFire: 3,
              energyCost: 15,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 500,
      shield: 1000,
      evasion: 0.2,
      regeneration: 8,
    },
    mobility: {
      speed: 80,
      turnRate: 3,
      acceleration: 40,
    },
    abilities: [
      {
        name: "Balance Restoration",
        description: "Creates a powerful shield around nearby allies",
        cooldown: 45,
        duration: 15,
        active: false,
        effect: SHIELD_FIELD_EFFECT,
      },
    ],
  },
  etherealGalleon: {
    health: 1300,
    maxHealth: 1300,
    shield: 1200,
    maxShield: 1200,
    energy: 800,
    maxEnergy: 800,
    speed: 100,
    turnRate: 3,
    cargo: 300,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "mgss-1",
        size: "medium" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "MGSS Cannon",
            category: "mgss",
            tier: 3,
            baseStats: {
              damage: 80,
              range: 1200,
              accuracy: 0.9,
              rateOfFire: 5,
              energyCost: 12,
              cooldown: 3,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: "weapons/mgss/advanced",
            mountRequirements: {
              size: "medium" as WeaponMountSize,
              power: 30,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 80,
              range: 1200,
              accuracy: 0.9,
              rateOfFire: 5,
              energyCost: 12,
              cooldown: 3,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 400,
      shield: 1200,
      evasion: 0.3,
      regeneration: 10,
    },
    mobility: {
      speed: 100,
      turnRate: 3,
      acceleration: 50,
    },
    abilities: [
      {
        name: "Ancient Energy",
        description: "Temporarily increases damage output",
        cooldown: 40,
        duration: 12,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  stellarEquinox: {
    health: 1100,
    maxHealth: 1100,
    shield: 900,
    maxShield: 900,
    energy: 700,
    maxEnergy: 700,
    speed: 110,
    turnRate: 2.5,
    cargo: 250,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "harmonic-1",
        size: "large" as WeaponMountSize,
        position: "turret" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["harmonicCannon"],
        currentWeapon: {
          config: {
            id: "harmonic-resonator",
            name: "Harmonic Resonator",
            category: "harmonicCannon",
            tier: 3,
            baseStats: {
              damage: 180,
              range: 1000,
              accuracy: 0.92,
              rateOfFire: 4,
              energyCost: 20,
              cooldown: 2.5,
              effects: [HARMONIC_EFFECT],
            },
            visualAsset: "weapons/harmonic/resonator",
            mountRequirements: {
              size: "large" as WeaponMountSize,
              power: 35,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 180,
              range: 1000,
              accuracy: 0.92,
              rateOfFire: 4,
              energyCost: 20,
              cooldown: 2.5,
              effects: [HARMONIC_EFFECT],
            },
            effects: [HARMONIC_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 350,
      shield: 900,
      evasion: 0.25,
      regeneration: 7,
    },
    mobility: {
      speed: 110,
      turnRate: 2.5,
      acceleration: 55,
    },
    abilities: [
      {
        name: "Harmonic Convergence",
        description: "Creates a field of resonating energy that damages and weakens enemy armor",
        cooldown: 35,
        duration: 12,
        active: false,
        effect: {
          type: "area",
          name: "Harmonic Convergence",
          description: "Resonating energy field",
          magnitude: 2,
          duration: 12,
          active: false,
          cooldown: 35,
          strength: 2,
          falloff: 0.5,
          radius: 400
        },
      },
    ],
  },
  chronosSentinel: {
    health: 900,
    maxHealth: 900,
    shield: 1100,
    maxShield: 1100,
    energy: 900,
    maxEnergy: 900,
    speed: 90,
    turnRate: 2,
    cargo: 200,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "temporal-1",
        size: "large" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["temporalCannon"],
        currentWeapon: {
          config: {
            id: "temporal-disruptor",
            name: "Temporal Disruptor",
            category: "temporalCannon",
            tier: 3,
            baseStats: {
              damage: 150,
              range: 1300,
              accuracy: 0.95,
              rateOfFire: 2,
              energyCost: 30,
              cooldown: 4,
              effects: [TEMPORAL_EFFECT],
            },
            visualAsset: "weapons/temporal/disruptor",
            mountRequirements: {
              size: "large" as WeaponMountSize,
              power: 45,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 150,
              range: 1300,
              accuracy: 0.95,
              rateOfFire: 2,
              energyCost: 30,
              cooldown: 4,
              effects: [TEMPORAL_EFFECT],
            },
            effects: [TEMPORAL_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 300,
      shield: 1100,
      evasion: 0.2,
      regeneration: 9,
    },
    mobility: {
      speed: 90,
      turnRate: 2,
      acceleration: 45,
    },
    abilities: [
      {
        name: "Time Dilation",
        description: "Creates a field that slows down time for enemies",
        cooldown: 40,
        duration: 10,
        active: false,
        effect: {
          type: "area",
          name: "Time Dilation",
          description: "Time dilation field",
          magnitude: 2.5,
          duration: 10,
          active: false,
          cooldown: 40,
          strength: 2.5,
          falloff: 0.5,
          radius: 600
        },
      },
    ],
  },
  nebulasJudgement: {
    health: 800,
    maxHealth: 800,
    shield: 1000,
    maxShield: 1000,
    energy: 800,
    maxEnergy: 800,
    speed: 130,
    turnRate: 3,
    cargo: 180,
    tier: 2,
    faction: "equator-horizon",
    weapons: [
      {
        id: "quantum-1",
        size: "medium" as WeaponMountSize,
        position: "turret" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["quantumCannon"],
        currentWeapon: {
          config: {
            id: "quantum-lance",
            name: "Quantum Lance",
            category: "quantumCannon",
            tier: 2,
            baseStats: {
              damage: 120,
              range: 900,
              accuracy: 0.9,
              rateOfFire: 3,
              energyCost: 25,
              cooldown: 3,
              effects: [QUANTUM_EFFECT],
            },
            visualAsset: "weapons/quantum/lance",
            mountRequirements: {
              size: "medium" as WeaponMountSize,
              power: 35,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 120,
              range: 900,
              accuracy: 0.9,
              rateOfFire: 3,
              energyCost: 25,
              cooldown: 3,
              effects: [QUANTUM_EFFECT],
            },
            effects: [QUANTUM_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 250,
      shield: 1000,
      evasion: 0.35,
      regeneration: 8,
    },
    mobility: {
      speed: 130,
      turnRate: 3,
      acceleration: 65,
    },
    abilities: [
      {
        name: "Quantum Entanglement",
        description: "Creates quantum distortions that bypass enemy shields",
        cooldown: 30,
        duration: 8,
        active: false,
        effect: {
          type: "area",
          name: "Quantum Entanglement",
          description: "Quantum distortion field",
          magnitude: 1.8,
          duration: 8,
          active: false,
          cooldown: 30,
          strength: 1.8,
          falloff: 0.5,
          radius: 300
        },
      },
    ],
  },
  aetherialHorizon: {
    health: 1400,
    maxHealth: 1400,
    shield: 1300,
    maxShield: 1300,
    energy: 800,
    maxEnergy: 800,
    speed: 110,
    turnRate: 3,
    cargo: 300,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "rocket-1",
        size: "large" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["rockets"],
        currentWeapon: {
          config: {
            id: "heavy-rockets",
            name: "Heavy Rockets",
            category: "rockets",
            tier: 3,
            baseStats: {
              damage: 280,
              range: 1600,
              accuracy: 0.85,
              rateOfFire: 2,
              energyCost: 20,
              cooldown: 4,
              effects: [EXPLOSIVE_EFFECT],
            },
            visualAsset: "weapons/rockets/heavy",
            mountRequirements: {
              size: "large" as WeaponMountSize,
              power: 45,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 280,
              range: 1600,
              accuracy: 0.85,
              rateOfFire: 2,
              energyCost: 20,
              cooldown: 4,
              effects: [EXPLOSIVE_EFFECT],
            },
            effects: [EXPLOSIVE_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 450,
      shield: 1300,
      evasion: 0.3,
      regeneration: 10,
    },
    mobility: {
      speed: 110,
      turnRate: 3,
      acceleration: 55,
    },
    abilities: [
      {
        name: "First Contact",
        description: "Creates a massive protective shield",
        cooldown: 55,
        duration: 18,
        active: false,
        effect: SHIELD_FIELD_EFFECT,
      },
    ],
  },
  cosmicCrusader: {
    health: 1200,
    maxHealth: 1200,
    shield: 1000,
    maxShield: 1000,
    energy: 700,
    maxEnergy: 700,
    speed: 130,
    turnRate: 3,
    cargo: 280,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "gauss-1",
        size: "large" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["gaussCannon"],
        currentWeapon: {
          config: {
            id: "gauss-cannon",
            name: "Gauss Cannon",
            category: "gaussCannon",
            tier: 3,
            baseStats: {
              damage: 220,
              range: 1400,
              accuracy: 0.94,
              rateOfFire: 3,
              energyCost: 18,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: "weapons/gauss/heavy",
            mountRequirements: {
              size: "large" as WeaponMountSize,
              power: 40,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 220,
              range: 1400,
              accuracy: 0.94,
              rateOfFire: 3,
              energyCost: 18,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 380,
      shield: 1000,
      evasion: 0.35,
      regeneration: 9,
    },
    mobility: {
      speed: 130,
      turnRate: 3,
      acceleration: 65,
    },
    abilities: [
      {
        name: "Threat Neutralization",
        description: "Unleashes a devastating attack",
        cooldown: 42,
        duration: 12,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  balancekeepersWrath: {
    health: 1600,
    maxHealth: 1600,
    shield: 1400,
    maxShield: 1400,
    energy: 900,
    maxEnergy: 900,
    speed: 70,
    turnRate: 3,
    cargo: 400,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "rail-1",
        size: "large" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "heavy-railgun",
            name: "Heavy Railgun",
            category: "railGun",
            tier: 3,
            baseStats: {
              damage: 350,
              range: 1800,
              accuracy: 0.96,
              rateOfFire: 2,
              energyCost: 25,
              cooldown: 4,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: "weapons/railgun/heavy",
            mountRequirements: {
              size: "large" as WeaponMountSize,
              power: 50,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 350,
              range: 1800,
              accuracy: 0.96,
              rateOfFire: 2,
              energyCost: 25,
              cooldown: 4,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 600,
      shield: 1400,
      evasion: 0.2,
      regeneration: 12,
    },
    mobility: {
      speed: 70,
      turnRate: 3,
      acceleration: 35,
    },
    abilities: [
      {
        name: "Wrath of Balance",
        description: "Unleashes devastating area damage",
        cooldown: 60,
        duration: 20,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  eclipticWatcher: {
    health: 800,
    maxHealth: 800,
    shield: 1000,
    maxShield: 1000,
    energy: 600,
    maxEnergy: 600,
    speed: 180,
    turnRate: 3,
    cargo: 200,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "mgss-1",
        size: "medium" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "MGSS Cannon",
            category: "mgss",
            tier: 3,
            baseStats: {
              damage: 100,
              range: 1000,
              accuracy: 0.92,
              rateOfFire: 6,
              energyCost: 10,
              cooldown: 3,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: "weapons/mgss/advanced",
            mountRequirements: {
              size: "medium" as WeaponMountSize,
              power: 25,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 100,
              range: 1000,
              accuracy: 0.92,
              rateOfFire: 6,
              energyCost: 10,
              cooldown: 3,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 250,
      shield: 1000,
      evasion: 0.5,
      regeneration: 8,
    },
    mobility: {
      speed: 180,
      turnRate: 3,
      acceleration: 90,
    },
    abilities: [
      {
        name: "Perfect Stealth",
        description: "Activates perfect stealth technology",
        cooldown: 38,
        duration: 10,
        active: false,
        effect: STEALTH_EFFECT,
      },
    ],
  },
  harmonysVanguard: {
    health: 1300,
    maxHealth: 1300,
    shield: 1100,
    maxShield: 1100,
    energy: 800,
    maxEnergy: 800,
    speed: 140,
    turnRate: 3,
    cargo: 300,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "gauss-1",
        size: "large" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["gaussCannon"],
        currentWeapon: {
          config: {
            id: "gauss-cannon",
            name: "Gauss Cannon",
            category: "gaussCannon",
            tier: 3,
            baseStats: {
              damage: 240,
              range: 1500,
              accuracy: 0.93,
              rateOfFire: 3,
              energyCost: 20,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: "weapons/gauss/heavy",
            mountRequirements: {
              size: "large" as WeaponMountSize,
              power: 45,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 240,
              range: 1500,
              accuracy: 0.93,
              rateOfFire: 3,
              energyCost: 20,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 420,
      shield: 1100,
      evasion: 0.35,
      regeneration: 10,
    },
    mobility: {
      speed: 140,
      turnRate: 3,
      acceleration: 70,
    },
    abilities: [
      {
        name: "Order from Chaos",
        description: "Creates a powerful shield field",
        cooldown: 48,
        duration: 15,
        active: false,
        effect: SHIELD_FIELD_EFFECT,
      },
    ],
  },
} as const; 