import { DamageEffect } from '../../effects/types_effects/WeaponEffects';
import {
  DAMAGE_BOOST_EFFECT,
  EXPLOSIVE_EFFECT,
  GAUSS_EFFECT,
  PLASMA_EFFECT,
  SHIELD_FIELD_EFFECT,
  SPEED_REDUCTION_EFFECT,
  STEALTH_EFFECT,
} from '../../effects/types_effects/shipEffects';
import { EquatorHorizonShipClass, FactionShipStats } from '../../types/ships/FactionShipTypes';
import {
  WeaponInstance,
  WeaponMountPosition,
  WeaponMountSize,
  WeaponStatus,
} from '../../types/weapons/WeaponTypes';

// Special weapon effects for Equator Horizon
const _TEMPORAL_EFFECT = {
  id: 'temporal-disruption',
  type: 'damage',
  name: 'Temporal Disruption',
  description: 'Time-warping energy damage',
  magnitude: 80,
  duration: 3,
  active: true,
  cooldown: 3.0,
  damage: 80,
  damageType: 'energy',
  penetration: 0.3,
  strength: 80,
} as DamageEffect;

const _QUANTUM_EFFECT = {
  id: 'quantum-collapse',
  type: 'damage',
  name: 'Quantum Collapse',
  description: 'Reality-warping energy damage',
  magnitude: 100,
  duration: 2,
  active: true,
  cooldown: 4.0,
  damage: 100,
  damageType: 'energy',
  penetration: 0.4,
  strength: 100,
} as DamageEffect;

const _HARMONIC_EFFECT = {
  id: 'harmonic-resonance',
  type: 'damage',
  name: 'Harmonic Resonance',
  description: 'Shield-penetrating harmonic damage',
  magnitude: 60,
  duration: 4,
  active: true,
  cooldown: 2.5,
  damage: 60,
  damageType: 'energy',
  penetration: 0.25,
  strength: 60,
} as DamageEffect;

export const EQUATOR_HORIZON_SHIPS: Record<EquatorHorizonShipClass, FactionShipStats> = {
  celestialArbiter: {
    health: 1500,
    maxHealth: 1500,
    shield: 1500,
    maxShield: 1500,
    energy: 1200,
    maxEnergy: 1200,
    speed: 90,
    turnRate: 1.5,
    cargo: 400,
    tier: 3,
    faction: 'equator-horizon',
    weapons: [
      {
        id: 'plasma-1',
        size: 'large' as WeaponMountSize,
        position: 'turret' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['plasmaCannon'],
        currentWeapon: {
          config: {
            id: 'ancient-plasma',
            name: 'Ancient Plasma Cannon',
            category: 'plasmaCannon',
            tier: 3,
            baseStats: {
              damage: 400,
              range: 1200,
              accuracy: 0.95,
              rateOfFire: 2,
              energyCost: 40,
              cooldown: 5,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: 'weapons/plasma/ancient',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 60,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 400,
              range: 1200,
              accuracy: 0.95,
              rateOfFire: 2,
              energyCost: 40,
              cooldown: 5,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 500,
      shield: 1500,
      evasion: 0.15,
      regeneration: 15,
    },
    mobility: {
      speed: 90,
      turnRate: 1.5,
      acceleration: 30,
    },
    abilities: [
      {
        name: 'Celestial Shield',
        description: 'Creates an impenetrable energy barrier',
        cooldown: 60,
        duration: 12,
        active: false,
        effect: SHIELD_FIELD_EFFECT,
      },
    ],
  },
  etherealGalleon: {
    health: 1200,
    maxHealth: 1200,
    shield: 1800,
    maxShield: 1800,
    energy: 1500,
    maxEnergy: 1500,
    speed: 70,
    turnRate: 1,
    cargo: 600,
    tier: 3,
    faction: 'equator-horizon',
    weapons: [
      {
        id: 'beam-1',
        size: 'large' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['beamWeapon'],
        currentWeapon: {
          config: {
            id: 'ancient-beam',
            name: 'Ancient Beam Weapon',
            category: 'beamWeapon',
            tier: 3,
            baseStats: {
              damage: 600,
              range: 1000,
              accuracy: 1,
              rateOfFire: 1,
              energyCost: 100,
              cooldown: 8,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: 'weapons/beam/ancient',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 80,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 600,
              range: 1000,
              accuracy: 1,
              rateOfFire: 1,
              energyCost: 100,
              cooldown: 8,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 400,
      shield: 1800,
      evasion: 0.1,
      regeneration: 20,
    },
    mobility: {
      speed: 70,
      turnRate: 1,
      acceleration: 20,
    },
    abilities: [
      {
        name: 'Energy Surge',
        description: 'Temporarily boosts weapon damage',
        cooldown: 45,
        duration: 15,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  stellarEquinox: {
    health: 900,
    maxHealth: 900,
    shield: 1200,
    maxShield: 1200,
    energy: 1000,
    maxEnergy: 1000,
    speed: 120,
    turnRate: 2,
    cargo: 300,
    tier: 2,
    faction: 'equator-horizon',
    weapons: [
      {
        id: 'pulse-1',
        size: 'medium' as WeaponMountSize,
        position: 'turret' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['pulseWeapon'],
        currentWeapon: {
          config: {
            id: 'ancient-pulse',
            name: 'Ancient Pulse Weapon',
            category: 'pulseWeapon',
            tier: 2,
            baseStats: {
              damage: 150,
              range: 800,
              accuracy: 0.9,
              rateOfFire: 4,
              energyCost: 20,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: 'weapons/pulse/ancient',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 40,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 150,
              range: 800,
              accuracy: 0.9,
              rateOfFire: 4,
              energyCost: 20,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 300,
      shield: 1200,
      evasion: 0.3,
      regeneration: 12,
    },
    mobility: {
      speed: 120,
      turnRate: 2,
      acceleration: 50,
    },
    abilities: [
      {
        name: 'Time Dilation',
        description: 'Slows nearby enemies',
        cooldown: 40,
        duration: 8,
        active: false,
        effect: SPEED_REDUCTION_EFFECT,
      },
    ],
  },
  chronosSentinel: {
    health: 800,
    maxHealth: 800,
    shield: 1000,
    maxShield: 1000,
    energy: 800,
    maxEnergy: 800,
    speed: 140,
    turnRate: 2.5,
    cargo: 200,
    tier: 2,
    faction: 'equator-horizon',
    weapons: [
      {
        id: 'disruptor-1',
        size: 'medium' as WeaponMountSize,
        position: 'turret' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['disruptor'],
        currentWeapon: {
          config: {
            id: 'ancient-disruptor',
            name: 'Ancient Disruptor',
            category: 'disruptor',
            tier: 2,
            baseStats: {
              damage: 120,
              range: 600,
              accuracy: 0.85,
              rateOfFire: 5,
              energyCost: 15,
              cooldown: 1,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: 'weapons/disruptor/ancient',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 35,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 120,
              range: 600,
              accuracy: 0.85,
              rateOfFire: 5,
              energyCost: 15,
              cooldown: 1,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 250,
      shield: 1000,
      evasion: 0.4,
      regeneration: 10,
    },
    mobility: {
      speed: 140,
      turnRate: 2.5,
      acceleration: 70,
    },
    abilities: [
      {
        name: 'Temporal Shield',
        description: 'Creates a shield that absorbs damage',
        cooldown: 30,
        duration: 6,
        active: false,
        effect: SHIELD_FIELD_EFFECT,
      },
    ],
  },
  nebulasJudgement: {
    health: 1000,
    maxHealth: 1000,
    shield: 1400,
    maxShield: 1400,
    energy: 1100,
    maxEnergy: 1100,
    speed: 100,
    turnRate: 1.8,
    cargo: 350,
    tier: 3,
    faction: 'equator-horizon',
    weapons: [
      {
        id: 'ion-1',
        size: 'large' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['ionCannon'],
        currentWeapon: {
          config: {
            id: 'ancient-ion',
            name: 'Ancient Ion Cannon',
            category: 'ionCannon',
            tier: 3,
            baseStats: {
              damage: 300,
              range: 1100,
              accuracy: 0.93,
              rateOfFire: 3,
              energyCost: 35,
              cooldown: 4,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: 'weapons/ion/ancient',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 55,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 300,
              range: 1100,
              accuracy: 0.93,
              rateOfFire: 3,
              energyCost: 35,
              cooldown: 4,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 350,
      shield: 1400,
      evasion: 0.25,
      regeneration: 14,
    },
    mobility: {
      speed: 100,
      turnRate: 1.8,
      acceleration: 40,
    },
    abilities: [
      {
        name: 'Judgement Beam',
        description: 'Fires a powerful beam of energy',
        cooldown: 50,
        duration: 3,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  aetherialHorizon: {
    health: 1400,
    maxHealth: 1400,
    shield: 1300,
    maxShield: 1300,
    energy: 800,
    maxEnergy: 800,
    speed: 110,
    turnRate: 3,
    cargo: 300,
    tier: 3,
    faction: 'equator-horizon',
    weapons: [
      {
        id: 'rocket-1',
        size: 'large' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['rockets'],
        currentWeapon: {
          config: {
            id: 'heavy-rockets',
            name: 'Heavy Rockets',
            category: 'rockets',
            tier: 3,
            baseStats: {
              damage: 280,
              range: 1600,
              accuracy: 0.85,
              rateOfFire: 2,
              energyCost: 20,
              cooldown: 4,
              effects: [EXPLOSIVE_EFFECT],
            },
            visualAsset: 'weapons/rockets/heavy',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 45,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 280,
              range: 1600,
              accuracy: 0.85,
              rateOfFire: 2,
              energyCost: 20,
              cooldown: 4,
              effects: [EXPLOSIVE_EFFECT],
            },
            effects: [EXPLOSIVE_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 450,
      shield: 1300,
      evasion: 0.3,
      regeneration: 10,
    },
    mobility: {
      speed: 110,
      turnRate: 3,
      acceleration: 55,
    },
    abilities: [
      {
        name: 'First Contact',
        description: 'Creates a massive protective shield',
        cooldown: 55,
        duration: 18,
        active: false,
        effect: SHIELD_FIELD_EFFECT,
      },
    ],
  },
  cosmicCrusader: {
    health: 1200,
    maxHealth: 1200,
    shield: 1000,
    maxShield: 1000,
    energy: 700,
    maxEnergy: 700,
    speed: 130,
    turnRate: 3,
    cargo: 280,
    tier: 3,
    faction: 'equator-horizon',
    weapons: [
      {
        id: 'gauss-1',
        size: 'large' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['gaussCannon'],
        currentWeapon: {
          config: {
            id: 'gauss-cannon',
            name: 'Gauss Cannon',
            category: 'gaussCannon',
            tier: 3,
            baseStats: {
              damage: 220,
              range: 1400,
              accuracy: 0.94,
              rateOfFire: 3,
              energyCost: 18,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: 'weapons/gauss/heavy',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 40,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 220,
              range: 1400,
              accuracy: 0.94,
              rateOfFire: 3,
              energyCost: 18,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 380,
      shield: 1000,
      evasion: 0.35,
      regeneration: 9,
    },
    mobility: {
      speed: 130,
      turnRate: 3,
      acceleration: 65,
    },
    abilities: [
      {
        name: 'Threat Neutralization',
        description: 'Unleashes a devastating attack',
        cooldown: 42,
        duration: 12,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  balancekeepersWrath: {
    health: 1600,
    maxHealth: 1600,
    shield: 1400,
    maxShield: 1400,
    energy: 900,
    maxEnergy: 900,
    speed: 70,
    turnRate: 3,
    cargo: 400,
    tier: 3,
    faction: 'equator-horizon',
    weapons: [
      {
        id: 'rail-1',
        size: 'large' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['railGun'],
        currentWeapon: {
          config: {
            id: 'heavy-railgun',
            name: 'Heavy Railgun',
            category: 'railGun',
            tier: 3,
            baseStats: {
              damage: 350,
              range: 1800,
              accuracy: 0.96,
              rateOfFire: 2,
              energyCost: 25,
              cooldown: 4,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: 'weapons/railgun/heavy',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 50,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 350,
              range: 1800,
              accuracy: 0.96,
              rateOfFire: 2,
              energyCost: 25,
              cooldown: 4,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 600,
      shield: 1400,
      evasion: 0.2,
      regeneration: 12,
    },
    mobility: {
      speed: 70,
      turnRate: 3,
      acceleration: 35,
    },
    abilities: [
      {
        name: 'Wrath of Balance',
        description: 'Unleashes devastating area damage',
        cooldown: 60,
        duration: 20,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  eclipticWatcher: {
    health: 800,
    maxHealth: 800,
    shield: 1000,
    maxShield: 1000,
    energy: 600,
    maxEnergy: 600,
    speed: 180,
    turnRate: 3,
    cargo: 200,
    tier: 3,
    faction: 'equator-horizon',
    weapons: [
      {
        id: 'mgss-1',
        size: 'medium' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['mgss'],
        currentWeapon: {
          config: {
            id: 'mgss-cannon',
            name: 'MGSS Cannon',
            category: 'mgss',
            tier: 3,
            baseStats: {
              damage: 100,
              range: 1000,
              accuracy: 0.92,
              rateOfFire: 6,
              energyCost: 10,
              cooldown: 3,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: 'weapons/mgss/advanced',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 25,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 100,
              range: 1000,
              accuracy: 0.92,
              rateOfFire: 6,
              energyCost: 10,
              cooldown: 3,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 250,
      shield: 1000,
      evasion: 0.5,
      regeneration: 8,
    },
    mobility: {
      speed: 180,
      turnRate: 3,
      acceleration: 90,
    },
    abilities: [
      {
        name: 'Perfect Stealth',
        description: 'Activates perfect stealth technology',
        cooldown: 38,
        duration: 10,
        active: false,
        effect: STEALTH_EFFECT,
      },
    ],
  },
  harmonysVanguard: {
    health: 1300,
    maxHealth: 1300,
    shield: 1100,
    maxShield: 1100,
    energy: 800,
    maxEnergy: 800,
    speed: 140,
    turnRate: 3,
    cargo: 300,
    tier: 3,
    faction: 'equator-horizon',
    weapons: [
      {
        id: 'gauss-1',
        size: 'large' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['gaussCannon'],
        currentWeapon: {
          config: {
            id: 'gauss-cannon',
            name: 'Gauss Cannon',
            category: 'gaussCannon',
            tier: 3,
            baseStats: {
              damage: 240,
              range: 1500,
              accuracy: 0.93,
              rateOfFire: 3,
              energyCost: 20,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: 'weapons/gauss/heavy',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 45,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 240,
              range: 1500,
              accuracy: 0.93,
              rateOfFire: 3,
              energyCost: 20,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 420,
      shield: 1100,
      evasion: 0.35,
      regeneration: 10,
    },
    mobility: {
      speed: 140,
      turnRate: 3,
      acceleration: 70,
    },
    abilities: [
      {
        name: 'Order from Chaos',
        description: 'Creates a powerful shield field',
        cooldown: 48,
        duration: 15,
        active: false,
        effect: SHIELD_FIELD_EFFECT,
      },
    ],
  },
} as const;
