import {
  DAMAGE_BOOST_EFFECT,
  EXPLOSIVE_EFFECT,
  GAUSS_EFFECT,
  PLASMA_EFFECT,
  SHIELD_FIELD_EFFECT,
  SPEED_BOOST_EFFECT,
  SPEED_REDUCTION_EFFECT,
  STEALTH_EFFECT,
} from '../../effects/types_effects/shipEffects';
import { FactionShipStats, LostNovaShipClass } from '../../types/ships/FactionShipTypes';
import {
  WeaponInstance,
  WeaponMountPosition,
  WeaponMountSize,
  WeaponStatus,
} from '../../types/weapons/WeaponTypes';

export const LOST_NOVA_SHIPS: Record<LostNovaShipClass, FactionShipStats> = {
  eclipseScythe: {
    health: 800,
    maxHealth: 800,
    shield: 800,
    maxShield: 800,
    energy: 600,
    maxEnergy: 600,
    speed: 150,
    turnRate: 3,
    cargo: 250,
    tier: 3,
    faction: 'lost-nova',
    weapons: [
      {
        id: 'gauss-1',
        size: 'medium' as WeaponMountSize,
        position: 'turret' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['gaussCannon'],
        currentWeapon: {
          config: {
            id: 'gauss-cannon',
            name: 'Gauss Cannon',
            category: 'gaussCannon',
            tier: 2,
            baseStats: {
              damage: 150,
              range: 1000,
              accuracy: 0.9,
              rateOfFire: 4,
              energyCost: 15,
              cooldown: 2,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: 'weapons/gauss/basic',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 35,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 150,
              range: 1000,
              accuracy: 0.9,
              rateOfFire: 4,
              energyCost: 15,
              cooldown: 2,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 200,
      shield: 800,
      evasion: 0.4,
      regeneration: 8,
    },
    mobility: {
      speed: 150,
      turnRate: 3,
      acceleration: 75,
    },
    abilities: [
      {
        id: 'phase-shift-ability',
        name: 'Phase Shift',
        description: 'Temporarily becomes untargetable',
        cooldown: 20,
        duration: 5,
        active: false,
        effect: STEALTH_EFFECT,
      },
    ],
  },
  nullsRevenge: {
    health: 1200,
    maxHealth: 1200,
    shield: 600,
    maxShield: 600,
    energy: 800,
    maxEnergy: 800,
    speed: 100,
    turnRate: 2,
    cargo: 300,
    tier: 3,
    faction: 'lost-nova',
    weapons: [
      {
        id: 'rail-1',
        size: 'large' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['railGun'],
        currentWeapon: {
          config: {
            id: 'heavy-railgun',
            name: 'Heavy Railgun',
            category: 'railGun',
            tier: 3,
            baseStats: {
              damage: 300,
              range: 1500,
              accuracy: 0.95,
              rateOfFire: 2,
              energyCost: 30,
              cooldown: 4,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: 'weapons/railgun/heavy',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 50,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 300,
              range: 1500,
              accuracy: 0.95,
              rateOfFire: 2,
              energyCost: 30,
              cooldown: 4,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 400,
      shield: 600,
      evasion: 0.2,
      regeneration: 5,
    },
    mobility: {
      speed: 100,
      turnRate: 2,
      acceleration: 40,
    },
    abilities: [
      {
        id: 'void-blast-ability',
        name: 'Void Blast',
        description: 'Unleashes a devastating energy blast',
        cooldown: 45,
        duration: 1,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  darkMatterReaper: {
    health: 700,
    maxHealth: 700,
    shield: 900,
    maxShield: 900,
    energy: 700,
    maxEnergy: 700,
    speed: 130,
    turnRate: 2.5,
    cargo: 200,
    tier: 2,
    faction: 'lost-nova',
    weapons: [
      {
        id: 'mgss-1',
        size: 'medium' as WeaponMountSize,
        position: 'turret' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['mgss'],
        currentWeapon: {
          config: {
            id: 'mgss-cannon',
            name: 'MGSS Cannon',
            category: 'mgss',
            tier: 2,
            baseStats: {
              damage: 40,
              range: 800,
              accuracy: 0.85,
              rateOfFire: 6,
              energyCost: 8,
              cooldown: 1,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: 'weapons/mgss/basic',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 25,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 40,
              range: 800,
              accuracy: 0.85,
              rateOfFire: 6,
              energyCost: 8,
              cooldown: 1,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 150,
      shield: 900,
      evasion: 0.35,
      regeneration: 10,
    },
    mobility: {
      speed: 130,
      turnRate: 2.5,
      acceleration: 60,
    },
    abilities: [
      {
        id: 'dark-matter-shield-ability',
        name: 'Dark Matter Shield',
        description: 'Creates an impenetrable shield',
        cooldown: 30,
        duration: 8,
        active: false,
        effect: SHIELD_FIELD_EFFECT,
      },
    ],
  },
  quantumPariah: {
    health: 600,
    maxHealth: 600,
    shield: 700,
    maxShield: 700,
    energy: 900,
    maxEnergy: 900,
    speed: 180,
    turnRate: 4,
    cargo: 150,
    tier: 2,
    faction: 'lost-nova',
    weapons: [
      {
        id: 'gauss-1',
        size: 'small' as WeaponMountSize,
        position: 'turret' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['gaussCannon'],
        currentWeapon: {
          config: {
            id: 'gauss-cannon',
            name: 'Gauss Cannon',
            category: 'gaussCannon',
            tier: 2,
            baseStats: {
              damage: 80,
              range: 900,
              accuracy: 0.9,
              rateOfFire: 3,
              energyCost: 10,
              cooldown: 2,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: 'weapons/gauss/basic',
            mountRequirements: {
              size: 'small' as WeaponMountSize,
              power: 20,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 80,
              range: 900,
              accuracy: 0.9,
              rateOfFire: 3,
              energyCost: 10,
              cooldown: 2,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 100,
      shield: 700,
      evasion: 0.5,
      regeneration: 7,
    },
    mobility: {
      speed: 180,
      turnRate: 4,
      acceleration: 90,
    },
    abilities: [
      {
        id: 'quantum-leap-ability',
        name: 'Quantum Leap',
        description: 'Instantly teleports a short distance',
        cooldown: 15,
        duration: 1,
        active: false,
        effect: SPEED_BOOST_EFFECT,
      },
    ],
  },
  entropyScale: {
    health: 900,
    maxHealth: 900,
    shield: 1000,
    maxShield: 1000,
    energy: 1000,
    maxEnergy: 1000,
    speed: 110,
    turnRate: 2,
    cargo: 250,
    tier: 3,
    faction: 'lost-nova',
    weapons: [
      {
        id: 'rail-1',
        size: 'large' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['railGun'],
        currentWeapon: {
          config: {
            id: 'advanced-railgun',
            name: 'Advanced Railgun',
            category: 'railGun',
            tier: 3,
            baseStats: {
              damage: 250,
              range: 1300,
              accuracy: 0.92,
              rateOfFire: 3,
              energyCost: 25,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: 'weapons/railgun/advanced',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 45,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 250,
              range: 1300,
              accuracy: 0.92,
              rateOfFire: 3,
              energyCost: 25,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 300,
      shield: 1000,
      evasion: 0.3,
      regeneration: 12,
    },
    mobility: {
      speed: 110,
      turnRate: 2,
      acceleration: 50,
    },
    abilities: [
      {
        id: 'entropy-field-ability',
        name: 'Entropy Field',
        description: 'Creates a field that slows enemies',
        cooldown: 35,
        duration: 10,
        active: false,
        effect: SPEED_REDUCTION_EFFECT,
      },
    ],
  },
  voidRevenant: {
    health: 750,
    maxHealth: 750,
    shield: 750,
    maxShield: 750,
    energy: 500,
    maxEnergy: 500,
    speed: 140,
    turnRate: 3,
    cargo: 180,
    tier: 2,
    faction: 'lost-nova',
    weapons: [
      {
        id: 'mgss-1',
        size: 'medium' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['mgss'],
        currentWeapon: {
          config: {
            id: 'mgss-cannon',
            name: 'MGSS Cannon',
            category: 'mgss',
            tier: 2,
            baseStats: {
              damage: 45,
              range: 850,
              accuracy: 0.85,
              rateOfFire: 6,
              energyCost: 8,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: 'weapons/mgss/basic',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 20,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 45,
              range: 850,
              accuracy: 0.85,
              rateOfFire: 6,
              energyCost: 8,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 200,
      shield: 750,
      evasion: 0.4,
      regeneration: 6,
    },
    mobility: {
      speed: 140,
      turnRate: 3,
      acceleration: 70,
    },
    abilities: [
      {
        id: 'void-jump-ability',
        name: 'Void Jump',
        description: 'Enables short-range teleportation',
        cooldown: 22,
        duration: 4,
        active: false,
        effect: STEALTH_EFFECT,
      },
    ],
  },
  scytheOfAndromeda: {
    health: 1000,
    maxHealth: 1000,
    shield: 1000,
    maxShield: 1000,
    energy: 700,
    maxEnergy: 700,
    speed: 130,
    turnRate: 3,
    cargo: 250,
    tier: 3,
    faction: 'lost-nova',
    weapons: [
      {
        id: 'rail-1',
        size: 'large' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['railGun'],
        currentWeapon: {
          config: {
            id: 'heavy-railgun',
            name: 'Heavy Railgun',
            category: 'railGun',
            tier: 3,
            baseStats: {
              damage: 200,
              range: 1300,
              accuracy: 0.92,
              rateOfFire: 3,
              energyCost: 18,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: 'weapons/railgun/heavy',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 40,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 200,
              range: 1300,
              accuracy: 0.92,
              rateOfFire: 3,
              energyCost: 18,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 350,
      shield: 1000,
      evasion: 0.35,
      regeneration: 8,
    },
    mobility: {
      speed: 130,
      turnRate: 3,
      acceleration: 65,
    },
    abilities: [
      {
        id: 'star-tear-ability',
        name: 'Star Tear',
        description: 'Unleashes a devastating area attack',
        cooldown: 45,
        duration: 10,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  nebularPersistence: {
    health: 950,
    maxHealth: 950,
    shield: 950,
    maxShield: 950,
    energy: 600,
    maxEnergy: 600,
    speed: 90,
    turnRate: 3,
    cargo: 200,
    tier: 3,
    faction: 'lost-nova',
    weapons: [
      {
        id: 'rocket-1',
        size: 'large' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['rockets'],
        currentWeapon: {
          config: {
            id: 'heavy-rockets',
            name: 'Heavy Rockets',
            category: 'rockets',
            tier: 3,
            baseStats: {
              damage: 180,
              range: 1000,
              accuracy: 0.8,
              rateOfFire: 2,
              energyCost: 15,
              cooldown: 4,
              effects: [EXPLOSIVE_EFFECT],
            },
            visualAsset: 'weapons/rockets/heavy',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 35,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 180,
              range: 1000,
              accuracy: 0.8,
              rateOfFire: 2,
              energyCost: 15,
              cooldown: 4,
              effects: [EXPLOSIVE_EFFECT],
            },
            effects: [EXPLOSIVE_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 300,
      shield: 950,
      evasion: 0.3,
      regeneration: 8,
    },
    mobility: {
      speed: 90,
      turnRate: 3,
      acceleration: 45,
    },
    abilities: [
      {
        id: 'nebula-shield-ability',
        name: 'Nebula Shield',
        description: 'Creates a powerful shield field',
        cooldown: 32,
        duration: 12,
        active: false,
        effect: SHIELD_FIELD_EFFECT,
      },
    ],
  },
  oblivionsWake: {
    health: 800,
    maxHealth: 800,
    shield: 800,
    maxShield: 800,
    energy: 500,
    maxEnergy: 500,
    speed: 160,
    turnRate: 3,
    cargo: 180,
    tier: 3,
    faction: 'lost-nova',
    weapons: [
      {
        id: 'gauss-1',
        size: 'medium' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['gaussCannon'],
        currentWeapon: {
          config: {
            id: 'gauss-cannon',
            name: 'Gauss Cannon',
            category: 'gaussCannon',
            tier: 3,
            baseStats: {
              damage: 140,
              range: 950,
              accuracy: 0.9,
              rateOfFire: 4,
              energyCost: 12,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: 'weapons/gauss/basic',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 30,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 140,
              range: 950,
              accuracy: 0.9,
              rateOfFire: 4,
              energyCost: 12,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 250,
      shield: 800,
      evasion: 0.4,
      regeneration: 7,
    },
    mobility: {
      speed: 160,
      turnRate: 3,
      acceleration: 80,
    },
    abilities: [
      {
        id: 'wake-of-destruction-ability',
        name: 'Wake of Destruction',
        description: 'Creates a destructive field',
        cooldown: 38,
        duration: 8,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  forbiddenVanguard: {
    health: 1200,
    maxHealth: 1200,
    shield: 1200,
    maxShield: 1200,
    energy: 700,
    maxEnergy: 700,
    speed: 120,
    turnRate: 3,
    cargo: 280,
    tier: 3,
    faction: 'lost-nova',
    weapons: [
      {
        id: 'mgss-1',
        size: 'medium' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['mgss'],
        currentWeapon: {
          config: {
            id: 'mgss-cannon',
            name: 'MGSS Cannon',
            category: 'mgss',
            tier: 3,
            baseStats: {
              damage: 70,
              range: 1100,
              accuracy: 0.88,
              rateOfFire: 5,
              energyCost: 10,
              cooldown: 3,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: 'weapons/mgss/advanced',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 25,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 70,
              range: 1100,
              accuracy: 0.88,
              rateOfFire: 5,
              energyCost: 10,
              cooldown: 3,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 400,
      shield: 1200,
      evasion: 0.3,
      regeneration: 10,
    },
    mobility: {
      speed: 120,
      turnRate: 3,
      acceleration: 60,
    },
    abilities: [
      {
        id: 'forbidden-technology-ability',
        name: 'Forbidden Technology',
        description: 'Unleashes devastating area damage',
        cooldown: 50,
        duration: 15,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
} as const;
