import { CommonShipDisplayStats } from "../../types/ships/CommonShipTypes";
import { FactionShipClass, FactionShipStats } from "../../types/ships/FactionShipTypes";
import { WeaponMount, WeaponMountSize, WeaponMountPosition, WeaponStatus } from "../../types/weapons/WeaponTypes";
import type { Effect } from "../../types/core/GameTypes";
import { ShipWeaponStats, ShipDefenseStats, ShipMobilityStats, ShipSystemStats, ShipAbility } from "../factions/factionShipStats";

// Add explicit type usage
type WeaponEffect = Effect;

export interface ShipStats {
  health: number;
  shield: number;
  armor: number;
  speed: number;
  turnRate: number;
  weapons: ShipWeaponStats[];
  defense: ShipDefenseStats;
  mobility: ShipMobilityStats;
  systems: ShipSystemStats;
  abilities: ShipAbility[];
}

export const SHIP_STATS: Record<FactionShipClass, FactionShipStats> = {
  // Space Rats Ships
  "rat-king": {
    health: 1000,
    maxHealth: 1000,
    shield: 500,
    maxShield: 500,
    energy: 500,
    maxEnergy: 500,
    speed: 100,
    turnRate: 2,
    cargo: 200,
    tier: 3,
    faction: "space-rats",
    weapons: [
      {
        id: "mgss-1",
        size: "medium",
        position: "front",
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "MGSS Cannon",
            category: "mgss",
            tier: 2,
            baseStats: {
              damage: 35,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 0.2,
              effects: [{ type: "plasma", damage: 20, duration: 4, magnitude: 1.2 }],
            },
            visualAsset: "weapons/mgss/basic",
            mountRequirements: {
              size: "medium",
              power: 20,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 35,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 0.2,
              effects: [{ type: "plasma", damage: 20, duration: 4, magnitude: 1.2 }],
            },
            effects: [{ type: "plasma", damage: 20, duration: 4, magnitude: 1.2 }],
          },
        },
      },
    ],
    defense: {
      armor: 300,
      shield: 500,
      evasion: 0.3,
      regeneration: 5,
    },
    mobility: {
      speed: 100,
      turnRate: 2,
      acceleration: 50,
    },
    abilities: [
      {
        name: "Pirate's Fury",
        description: "Increases weapon damage for a short duration",
        cooldown: 30,
        duration: 10,
        active: false,
        effect: { type: "damage", magnitude: 2, duration: 10 },
      },
    ],
  },
  "asteroid-marauder": {
    health: 600,
    maxHealth: 600,
    shield: 300,
    maxShield: 300,
    energy: 400,
    maxEnergy: 400,
    speed: 120,
    turnRate: 3,
    cargo: 150,
    weapons: [
      {
        id: "mg-1",
        size: "small" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["machineGun"],
        currentWeapon: {
          config: {
            id: "basic-mg",
            name: "Basic Machine Gun",
            category: "machineGun",
            tier: 1,
            baseStats: {
              damage: 30,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 2,
              cooldown: 0.2,
              effects: [],
            },
            visualAsset: "weapons/machinegun/basic",
            mountRequirements: {
              size: "small" as WeaponMountSize,
              power: 10,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 30,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 2,
              cooldown: 0.2,
              effects: [],
            },
            effects: [],
          },
        },
      },
    ],
    defense: {
      armor: 200,
      shield: 300,
      evasion: 0.4,
      regeneration: 3,
    },
    mobility: {
      speed: 120,
      turnRate: 3,
      acceleration: 60,
    },
    abilities: [
      {
        name: "Scavenger Boost",
        description: "Temporarily increases movement speed",
        cooldown: 15,
        duration: 5,
        active: false,
        effect: { type: "speed", magnitude: 1.5, duration: 5 },
      },
    ],
    tier: 2,
    faction: "space-rats",
  },
  "rogue-nebula": {
    health: 500,
    maxHealth: 500,
    shield: 400,
    maxShield: 400,
    energy: 450,
    maxEnergy: 450,
    speed: 150,
    turnRate: 3.5,
    cargo: 150,
    weapons: [
      {
        id: "railgun-1",
        size: "medium" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "advanced-railgun",
            name: "Advanced Railgun",
            category: "railGun",
            tier: 2,
            baseStats: {
              damage: 200,
              range: 1100,
              accuracy: 0.85,
              rateOfFire: 5,
              energyCost: 8,
              cooldown: 0.3,
              effects: [{ type: "gauss", damage: 50, duration: 2, magnitude: 1.5 }],
            },
            visualAsset: "weapons/railgun/advanced",
            mountRequirements: {
              size: "medium" as WeaponMountSize,
              power: 25,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 200,
              range: 1100,
              accuracy: 0.85,
              rateOfFire: 5,
              energyCost: 8,
              cooldown: 0.3,
              effects: [{ type: "gauss", damage: 50, duration: 2, magnitude: 1.5 }],
            },
            effects: [{ type: "gauss", damage: 50, duration: 2, magnitude: 1.5 }],
          },
        },
      },
    ],
    defense: {
      armor: 150,
      shield: 400,
      evasion: 0.4,
      regeneration: 4,
    },
    mobility: {
      speed: 150,
      turnRate: 3.5,
      acceleration: 65,
    },
    abilities: [
      {
        name: "Stealth Drive",
        description: "Temporarily increases stealth capabilities",
        cooldown: 25,
        duration: 8,
        active: false,
        effect: { type: "stealth", magnitude: 1, duration: 8 },
      },
    ],
    tier: 2,
    faction: "space-rats",
  },
  "rats-revenge": {
    health: 800,
    maxHealth: 800,
    shield: 400,
    maxShield: 400,
    energy: 400,
    maxEnergy: 400,
    speed: 130,
    turnRate: 3,
    cargo: 200,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "mgss-1",
        type: "mgss",
        size: "medium",
        position: "turret",
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "mgss Cannon",
            category: "mgss",
            tier: 2,
            baseStats: {
              damage: 40,
              range: 700,
              accuracy: 0.75,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 2,
              effects: [{ type: "plasma", magnitude: 1.2, duration: 2 }],
            },
            visualAsset: "weapons/mgss/basic",
            mountRequirements: {
              size: "medium",
              power: 20,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 40,
              range: 700,
              accuracy: 0.75,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 2,
              effects: [{ type: "plasma", magnitude: 1.2, duration: 2 }],
            },
            effects: [{ type: "plasma", magnitude: 1.2, duration: 2 }],
          },
        },
      },
    ],
    defense: {
      armor: 250,
      shield: 400,
      evasion: 0.3,
      regeneration: 5,
    },
    mobility: {
      speed: 130,
      turnRate: 3,
      acceleration: 65,
    },
    abilities: [
      {
        name: "Vengeful Strike",
        description: "Increases damage output temporarily",
        cooldown: 20,
        duration: 5,
        active: false,
        effect: { type: "damage", magnitude: 1.5, duration: 5 },
      },
    ],
  },
  "dark-sector-corsair": {
    health: 550,
    maxHealth: 550,
    shield: 350,
    maxShield: 350,
    energy: 400,
    maxEnergy: 400,
    speed: 140,
    turnRate: 3,
    cargo: 150,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "gauss-1",
        size: "medium",
        position: "front",
        rotation: 0,
        allowedCategories: ["gaussCannon"],
        currentWeapon: {
          config: {
            id: "gauss-cannon",
            name: "Gauss Cannon",
            category: "gaussCannon",
            tier: 2,
            baseStats: {
              damage: 90,
              range: 850,
              accuracy: 0.9,
              rateOfFire: 5,
              energyCost: 8,
              cooldown: 2,
              effects: [{ type: "gauss", damage: 20, duration: 3, magnitude: 1.2 }],
            },
            visualAsset: "weapons/gauss/basic",
            mountRequirements: {
              size: "medium",
              power: 25,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 90,
              range: 850,
              accuracy: 0.9,
              rateOfFire: 5,
              energyCost: 8,
              cooldown: 2,
              effects: [{ type: "gauss", damage: 20, duration: 3, magnitude: 1.2 }],
            },
            effects: [{ type: "gauss", damage: 20, duration: 3, magnitude: 1.2 }],
          },
        },
      },
    ],
    defense: {
      armor: 180,
      shield: 350,
      evasion: 0.4,
      regeneration: 3,
    },
    mobility: {
      speed: 140,
      turnRate: 3,
      acceleration: 60,
    },
    abilities: [
      {
        name: "Shadow Strike",
        description: "Temporarily increases stealth capabilities",
        cooldown: 18,
        duration: 4,
        active: false,
        effect: { type: "stealth", magnitude: 0.8, duration: 4 },
      },
    ],
  },
  "wailing-wreck": {
    health: 900,
    maxHealth: 900,
    shield: 200,
    maxShield: 200,
    energy: 500,
    maxEnergy: 500,
    speed: 80,
    turnRate: 2,
    cargo: 180,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "rocket-1",
        size: "large",
        position: "front",
        rotation: 0,
        allowedCategories: ["rockets"],
        currentWeapon: {
          config: {
            id: "heavy-rockets",
            name: "Heavy Rockets",
            category: "rockets",
            tier: 2,
            baseStats: {
              damage: 150,
              range: 1000,
              accuracy: 0.7,
              rateOfFire: 2,
              energyCost: 12,
              cooldown: 4,
              effects: [{ type: "explosive", magnitude: 1.8, duration: 2, radius: 60 }],
            },
            visualAsset: "weapons/rockets/heavy",
            mountRequirements: {
              size: "large",
              power: 35,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 150,
              range: 1000,
              accuracy: 0.7,
              rateOfFire: 2,
              energyCost: 12,
              cooldown: 4,
              effects: [{ type: "explosive", magnitude: 1.8, duration: 2, radius: 60 }],
            },
            effects: [{ type: "explosive", magnitude: 1.8, duration: 2, radius: 60 }],
          },
        },
      },
    ],
    defense: {
      armor: 400,
      shield: 200,
      evasion: 0.2,
      regeneration: 2,
    },
    mobility: {
      speed: 80,
      turnRate: 2,
      acceleration: 40,
    },
    abilities: [
      {
        name: "Sonic Disruption",
        description: "Slows down nearby enemies",
        cooldown: 35,
        duration: 8,
        active: false,
        effect: { type: "speed", magnitude: 0.5, duration: 8 },
      },
    ],
  },
  "galactic-scourge": {
    health: 1200,
    maxHealth: 1200,
    shield: 600,
    maxShield: 600,
    energy: 700,
    maxEnergy: 700,
    speed: 90,
    turnRate: 3,
    cargo: 250,
    tier: 3,
    faction: "space-rats",
    weapons: [
      {
        id: "rail-1",
        size: "large",
        position: "front",
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "heavy-railgun",
            name: "Heavy Railgun",
            category: "railGun",
            tier: 3,
            baseStats: {
              damage: 200,
              range: 1100,
              accuracy: 0.85,
              rateOfFire: 3,
              energyCost: 15,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.5, duration: 2 }],
            },
            visualAsset: "weapons/railgun/heavy",
            mountRequirements: {
              size: "large",
              power: 35,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 200,
              range: 1100,
              accuracy: 0.85,
              rateOfFire: 3,
              energyCost: 15,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.5, duration: 2 }],
            },
            effects: [{ type: "gauss", magnitude: 1.5, duration: 2 }],
          },
        },
      },
    ],
    defense: {
      armor: 350,
      shield: 600,
      evasion: 0.3,
      regeneration: 5,
    },
    mobility: {
      speed: 90,
      turnRate: 3,
      acceleration: 45,
    },
    abilities: [
      {
        name: "Chaos Wave",
        description: "Unleashes a devastating wave of energy",
        cooldown: 40,
        duration: 12,
        active: false,
        effect: { type: "damage", magnitude: 1.8, duration: 12, radius: 300 },
      },
    ],
  },
  "plasma-fang": {
    health: 450,
    maxHealth: 450,
    shield: 300,
    maxShield: 300,
    energy: 400,
    maxEnergy: 400,
    speed: 160,
    turnRate: 3,
    cargo: 150,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "mgss-1",
        type: "mgss",
        size: "medium",
        position: "turret",
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "mgss Cannon",
            category: "mgss",
            tier: 2,
            baseStats: {
              damage: 35,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 2,
              effects: [{ type: "plasma", magnitude: 1.2, duration: 4, damage: 20 }],
            },
            visualAsset: "weapons/mgss/basic",
            mountRequirements: {
              size: "medium",
              power: 20,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 35,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 2,
              effects: [{ type: "plasma", magnitude: 1.2, duration: 4, damage: 20 }],
            },
            effects: [{ type: "plasma", magnitude: 1.2, duration: 4, damage: 20 }],
          },
        },
      },
    ],
    defense: {
      armor: 150,
      shield: 300,
      evasion: 0.5,
      regeneration: 4,
    },
    mobility: {
      speed: 160,
      turnRate: 3,
      acceleration: 80,
    },
    abilities: [
      {
        name: "Plasma Burst",
        description: "Releases a concentrated burst of plasma energy",
        cooldown: 22,
        duration: 6,
        active: false,
        effect: { type: "damage", magnitude: 1.6, duration: 6 },
      },
    ],
  },
  "vermin-vanguard": {
    health: 700,
    maxHealth: 700,
    shield: 450,
    maxShield: 450,
    energy: 400,
    maxEnergy: 400,
    speed: 110,
    turnRate: 3,
    cargo: 200,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "gauss-1",
        size: "medium",
        position: "front",
        rotation: 0,
        allowedCategories: ["gaussCannon"],
        currentWeapon: {
          config: {
            id: "gauss-cannon",
            name: "Gauss Cannon",
            category: "gaussCannon",
            tier: 2,
            baseStats: {
              damage: 100,
              range: 950,
              accuracy: 0.88,
              rateOfFire: 2,
              energyCost: 25,
              cooldown: 2,
              effects: [{ type: "gauss", damage: 25, duration: 3, magnitude: 1.5 }],
            },
            visualAsset: "weapons/gauss/basic",
            mountRequirements: {
              size: "medium",
              power: 30,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 100,
              range: 950,
              accuracy: 0.88,
              rateOfFire: 2,
              energyCost: 25,
              cooldown: 2,
              effects: [{ type: "gauss", damage: 25, duration: 3, magnitude: 1.5 }],
            },
            effects: [{ type: "gauss", damage: 25, duration: 3, magnitude: 1.5 }],
          },
        },
      },
    ],
    defense: {
      armor: 250,
      shield: 450,
      evasion: 0.3,
      regeneration: 5,
    },
    mobility: {
      speed: 110,
      turnRate: 3,
      acceleration: 55,
    },
    abilities: [
      {
        name: "Rally Vermin",
        description: "Increases speed of nearby allies",
        cooldown: 28,
        duration: 10,
        active: false,
        effect: { type: "speed", magnitude: 1.3, duration: 10, radius: 200 },
      },
    ],
  },
  "black-void-buccaneer": {
    health: 600,
    maxHealth: 600,
    shield: 500,
    maxShield: 500,
    energy: 450,
    maxEnergy: 450,
    speed: 135,
    turnRate: 3,
    cargo: 180,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "rail-1",
        size: "medium",
        position: "front",
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "railgun",
            name: "Railgun",
            category: "railGun",
            tier: 2,
            baseStats: {
              damage: 140,
              range: 1000,
              accuracy: 0.9,
              rateOfFire: 3,
              energyCost: 12,
              cooldown: 3,
              effects: [{ type: "gauss", damage: 35, duration: 2, magnitude: 1.4 }],
            },
            visualAsset: "weapons/railgun/basic",
            mountRequirements: {
              size: "medium",
              power: 30,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 140,
              range: 1000,
              accuracy: 0.9,
              rateOfFire: 3,
              energyCost: 12,
              cooldown: 3,
              effects: [{ type: "gauss", damage: 35, duration: 2, magnitude: 1.4 }],
            },
            effects: [{ type: "gauss", damage: 35, duration: 2, magnitude: 1.4 }],
          },
        },
      },
    ],
    defense: {
      armor: 200,
      shield: 500,
      evasion: 0.4,
      regeneration: 4,
    },
    mobility: {
      speed: 135,
      turnRate: 3,
      acceleration: 65,
    },
    abilities: [
      {
        name: "Void Cloak",
        description: "Activates stealth capabilities",
        cooldown: 32,
        duration: 7,
        active: false,
        effect: { type: "stealth", magnitude: 0.9, duration: 7 },
      },
    ],
  },

  // Lost Nova Ships
  "eclipse-scythe": {
    health: 800,
    maxHealth: 800,
    shield: 800,
    maxShield: 800,
    energy: 600,
    maxEnergy: 600,
    speed: 150,
    turnRate: 3,
    cargo: 250,
    tier: 3,
    faction: "lost-nova",
    weapons: [
      {
        id: "gauss-1",
        type: "gaussCannon",
        size: "medium",
        position: "turret",
        rotation: 0,
        allowedCategories: ["gaussCannon"],
        currentWeapon: {
          config: {
            id: "gauss-cannon",
            name: "Gauss Cannon",
            category: "gaussCannon",
            tier: 2,
            baseStats: {
              damage: 150,
              range: 1000,
              accuracy: 0.9,
              rateOfFire: 4,
              energyCost: 15,
              cooldown: 2,
              effects: [{ type: "gauss", magnitude: 1.5, duration: 2, damage: 50 }],
            },
            visualAsset: "weapons/gauss/basic",
            mountRequirements: {
              size: "medium",
              power: 35,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 150,
              range: 1000,
              accuracy: 0.9,
              rateOfFire: 4,
              energyCost: 15,
              cooldown: 2,
              effects: [{ type: "gauss", magnitude: 1.5, duration: 2, damage: 50 }],
            },
            effects: [{ type: "gauss", magnitude: 1.5, duration: 2, damage: 50 }],
          },
        },
      },
    ],
    defense: {
      armor: 200,
      shield: 800,
      evasion: 0.4,
      regeneration: 6,
    },
    mobility: {
      speed: 150,
      turnRate: 3,
      acceleration: 75,
    },
    abilities: [
      {
        name: "Phase Shift",
        description: "Temporarily becomes untargetable",
        cooldown: 20,
        duration: 5,
        active: false,
        effect: { type: "stealth", magnitude: 1, duration: 5 },
      },
    ],
  },
  "nulls-revenge": {
    health: 1100,
    maxHealth: 1100,
    shield: 900,
    maxShield: 900,
    energy: 700,
    maxEnergy: 700,
    speed: 100,
    turnRate: 3,
    cargo: 250,
    tier: 3,
    faction: "lost-nova",
    weapons: [
      {
        id: "rail-1",
        size: "large",
        position: "front",
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "heavy-railgun",
            name: "Heavy Railgun",
            category: "railGun",
            tier: 3,
            baseStats: {
              damage: 180,
              range: 1200,
              accuracy: 0.85,
              rateOfFire: 3,
              energyCost: 15,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.5, duration: 3 }],
            },
            visualAsset: "weapons/railgun/heavy",
            mountRequirements: {
              size: "large",
              power: 35,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 180,
              range: 1200,
              accuracy: 0.85,
              rateOfFire: 3,
              energyCost: 15,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.5, duration: 3 }],
            },
            effects: [{ type: "gauss", magnitude: 1.5, duration: 3 }],
          },
        },
      },
    ],
    defense: {
      armor: 300,
      shield: 900,
      evasion: 0.3,
      regeneration: 8,
    },
    mobility: {
      speed: 100,
      turnRate: 3,
      acceleration: 50,
    },
    abilities: [
      {
        name: "Null Field",
        description: "Creates a powerful shield field",
        cooldown: 35,
        duration: 8,
        active: false,
        effect: { type: "shield", magnitude: 2, duration: 8 },
      },
    ],
  },
  "dark-matter-reaper": {
    health: 900,
    maxHealth: 900,
    shield: 700,
    maxShield: 700,
    energy: 600,
    maxEnergy: 600,
    speed: 120,
    turnRate: 3,
    cargo: 300,
    tier: 3,
    faction: "lost-nova",
    weapons: [
      {
        id: "mgss-1",
        type: "mgss",
        size: "medium",
        position: "turret",
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "mgss Cannon",
            category: "mgss",
            tier: 2,
            baseStats: {
              damage: 60,
              range: 900,
              accuracy: 0.8,
              rateOfFire: 6,
              energyCost: 8,
              cooldown: 3,
              effects: [{ type: "plasma", magnitude: 1.5, duration: 4 }],
            },
            visualAsset: "weapons/mgss/basic",
            mountRequirements: {
              size: "medium",
              power: 25,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 60,
              range: 900,
              accuracy: 0.8,
              rateOfFire: 6,
              energyCost: 8,
              cooldown: 3,
              effects: [{ type: "plasma", magnitude: 1.5, duration: 4 }],
            },
            effects: [{ type: "plasma", magnitude: 1.5, duration: 4 }],
          },
        },
      },
    ],
    defense: {
      armor: 250,
      shield: 700,
      evasion: 0.35,
      regeneration: 7,
    },
    mobility: {
      speed: 120,
      turnRate: 3,
      acceleration: 60,
    },
    abilities: [
      {
        name: "Dark Matter Burst",
        description: "Unleashes a burst of dark matter energy",
        cooldown: 30,
        duration: 6,
        active: false,
        effect: { type: "damage", magnitude: 1.8, duration: 6, radius: 250 },
      },
    ],
  },
  "quantum-pariah": {
    health: 600,
    maxHealth: 600,
    shield: 600,
    maxShield: 600,
    energy: 500,
    maxEnergy: 500,
    speed: 170,
    turnRate: 3,
    cargo: 150,
    tier: 2,
    faction: "lost-nova",
    weapons: [
      {
        id: "gauss-1",
        size: "medium",
        position: "front",
        rotation: 0,
        allowedCategories: ["gaussCannon"],
        currentWeapon: {
          config: {
            id: "gauss-cannon",
            name: "Gauss Cannon",
            category: "gaussCannon",
            tier: 2,
            baseStats: {
              damage: 100,
              range: 800,
              accuracy: 0.95,
              rateOfFire: 4,
              energyCost: 10,
              cooldown: 2,
              effects: [{ type: "gauss", magnitude: 1.2, duration: 2 }],
            },
            visualAsset: "weapons/gauss/basic",
            mountRequirements: {
              size: "medium",
              power: 25,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 100,
              range: 800,
              accuracy: 0.95,
              rateOfFire: 4,
              energyCost: 10,
              cooldown: 2,
              effects: [{ type: "gauss", magnitude: 1.2, duration: 2 }],
            },
            effects: [{ type: "gauss", magnitude: 1.2, duration: 2 }],
          },
        },
      },
    ],
    defense: {
      armor: 150,
      shield: 600,
      evasion: 0.5,
      regeneration: 6,
    },
    mobility: {
      speed: 170,
      turnRate: 3,
      acceleration: 85,
    },
    abilities: [
      {
        name: "Quantum Cloak",
        description: "Activates advanced stealth technology",
        cooldown: 25,
        duration: 7,
        active: false,
        effect: { type: "stealth", magnitude: 1, duration: 7 },
      },
    ],
  },
  "entropy-scale": {
    health: 850,
    maxHealth: 850,
    shield: 850,
    maxShield: 850,
    energy: 600,
    maxEnergy: 600,
    speed: 110,
    turnRate: 3,
    cargo: 200,
    tier: 3,
    faction: "lost-nova",
    weapons: [
      {
        id: "rail-1",
        size: "medium",
        position: "front",
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "railgun",
            name: "Railgun",
            category: "railGun",
            tier: 2,
            baseStats: {
              damage: 160,
              range: 1100,
              accuracy: 0.88,
              rateOfFire: 4,
              energyCost: 12,
              cooldown: 2,
              effects: [{ type: "gauss", magnitude: 1.3, duration: 3 }],
            },
            visualAsset: "weapons/railgun/basic",
            mountRequirements: {
              size: "medium",
              power: 30,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 160,
              range: 1100,
              accuracy: 0.88,
              rateOfFire: 4,
              energyCost: 12,
              cooldown: 2,
              effects: [{ type: "gauss", magnitude: 1.3, duration: 3 }],
            },
            effects: [{ type: "gauss", magnitude: 1.3, duration: 3 }],
          },
        },
      },
    ],
    defense: {
      armor: 280,
      shield: 850,
      evasion: 0.35,
      regeneration: 7,
    },
    mobility: {
      speed: 110,
      turnRate: 3,
      acceleration: 55,
    },
    abilities: [
      {
        name: "Entropy Field",
        description: "Creates a field that slows enemies",
        cooldown: 28,
        duration: 9,
        active: false,
        effect: { type: "speed", magnitude: 0.6, duration: 9, radius: 300 },
      },
    ],
  },
  "void-revenant": {
    health: 750,
    maxHealth: 750,
    shield: 750,
    maxShield: 750,
    energy: 500,
    maxEnergy: 500,
    speed: 140,
    turnRate: 3,
    cargo: 180,
    tier: 2,
    faction: "lost-nova",
    weapons: [
      {
        id: "mgss-1",
        size: "medium",
        position: "front",
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "mgss Cannon",
            category: "mgss",
            tier: 2,
            baseStats: {
              damage: 45,
              range: 850,
              accuracy: 0.85,
              rateOfFire: 6,
              energyCost: 8,
              cooldown: 2,
              effects: [{ type: "plasma", magnitude: 1.2, duration: 3 }],
            },
            visualAsset: "weapons/mgss/basic",
            mountRequirements: {
              size: "medium",
              power: 20,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 45,
              range: 850,
              accuracy: 0.85,
              rateOfFire: 6,
              energyCost: 8,
              cooldown: 2,
              effects: [{ type: "plasma", magnitude: 1.2, duration: 3 }],
            },
            effects: [{ type: "plasma", magnitude: 1.2, duration: 3 }],
          },
        },
      },
    ],
    defense: {
      armor: 200,
      shield: 750,
      evasion: 0.4,
      regeneration: 6,
    },
    mobility: {
      speed: 140,
      turnRate: 3,
      acceleration: 70,
    },
    abilities: [
      {
        name: "Void Jump",
        description: "Enables short-range teleportation",
        cooldown: 22,
        duration: 4,
        active: false,
        effect: { type: "stealth", magnitude: 0.9, duration: 4 },
      },
    ],
  },
  "scythe-of-andromeda": {
    health: 1000,
    maxHealth: 1000,
    shield: 1000,
    maxShield: 1000,
    energy: 700,
    maxEnergy: 700,
    speed: 130,
    turnRate: 3,
    cargo: 250,
    tier: 3,
    faction: "lost-nova",
    weapons: [
      {
        id: "rail-1",
        size: "large",
        position: "front",
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "heavy-railgun",
            name: "Heavy Railgun",
            category: "railGun",
            tier: 3,
            baseStats: {
              damage: 200,
              range: 1300,
              accuracy: 0.92,
              rateOfFire: 3,
              energyCost: 18,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.6, duration: 4 }],
            },
            visualAsset: "weapons/railgun/heavy",
            mountRequirements: {
              size: "large",
              power: 40,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 200,
              range: 1300,
              accuracy: 0.92,
              rateOfFire: 3,
              energyCost: 18,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.6, duration: 4 }],
            },
            effects: [{ type: "gauss", magnitude: 1.6, duration: 4 }],
          },
        },
      },
    ],
    defense: {
      armor: 350,
      shield: 1000,
      evasion: 0.35,
      regeneration: 8,
    },
    mobility: {
      speed: 130,
      turnRate: 3,
      acceleration: 65,
    },
    abilities: [
      {
        name: "Star Tear",
        description: "Unleashes a devastating area attack",
        cooldown: 45,
        duration: 10,
        active: false,
        effect: { type: "damage", magnitude: 2.2, duration: 10, radius: 400 },
      },
    ],
  },
  "nebular-persistence": {
    health: 950,
    maxHealth: 950,
    shield: 950,
    maxShield: 950,
    energy: 600,
    maxEnergy: 600,
    speed: 90,
    turnRate: 3,
    cargo: 200,
    tier: 3,
    faction: "lost-nova",
    weapons: [
      {
        id: "rocket-1",
        size: "large",
        position: "front",
        rotation: 0,
        allowedCategories: ["rockets"],
        currentWeapon: {
          config: {
            id: "heavy-rockets",
            name: "Heavy Rockets",
            category: "rockets",
            tier: 3,
            baseStats: {
              damage: 180,
              range: 1000,
              accuracy: 0.8,
              rateOfFire: 2,
              energyCost: 15,
              cooldown: 4,
              effects: [{ type: "explosive", magnitude: 1.8, duration: 2, radius: 60 }],
            },
            visualAsset: "weapons/rockets/heavy",
            mountRequirements: {
              size: "large",
              power: 35,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 180,
              range: 1000,
              accuracy: 0.8,
              rateOfFire: 2,
              energyCost: 15,
              cooldown: 4,
              effects: [{ type: "explosive", magnitude: 1.8, duration: 2, radius: 60 }],
            },
            effects: [{ type: "explosive", magnitude: 1.8, duration: 2, radius: 60 }],
          },
        },
      },
    ],
    defense: {
      armor: 300,
      shield: 950,
      evasion: 0.3,
      regeneration: 8,
    },
    mobility: {
      speed: 90,
      turnRate: 3,
      acceleration: 45,
    },
    abilities: [
      {
        name: "Nebula Shield",
        description: "Creates a powerful shield field",
        cooldown: 32,
        duration: 12,
        active: false,
        effect: { type: "shield", magnitude: 1.8, duration: 12 },
      },
    ],
  },
  "oblivions-wake": {
    health: 800,
    maxHealth: 800,
    shield: 800,
    maxShield: 800,
    energy: 500,
    maxEnergy: 500,
    speed: 160,
    turnRate: 3,
    cargo: 180,
    tier: 3,
    faction: "lost-nova",
    weapons: [
      {
        id: "gauss-1",
        size: "medium",
        position: "front",
        rotation: 0,
        allowedCategories: ["gaussCannon"],
        currentWeapon: {
          config: {
            id: "gauss-cannon",
            name: "Gauss Cannon",
            category: "gaussCannon",
            tier: 3,
            baseStats: {
              damage: 140,
              range: 950,
              accuracy: 0.9,
              rateOfFire: 4,
              energyCost: 12,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.4, duration: 3 }],
            },
            visualAsset: "weapons/gauss/basic",
            mountRequirements: {
              size: "medium",
              power: 30,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 140,
              range: 950,
              accuracy: 0.9,
              rateOfFire: 4,
              energyCost: 12,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.4, duration: 3 }],
            },
            effects: [{ type: "gauss", magnitude: 1.4, duration: 3 }],
          },
        },
      },
    ],
    defense: {
      armor: 250,
      shield: 800,
      evasion: 0.4,
      regeneration: 7,
    },
    mobility: {
      speed: 160,
      turnRate: 3,
      acceleration: 80,
    },
    abilities: [
      {
        name: "Wake of Destruction",
        description: "Creates a destructive field",
        cooldown: 38,
        duration: 8,
        active: false,
        effect: { type: "damage", magnitude: 1.6, duration: 8, radius: 200 },
      },
    ],
  },
  "forbidden-vanguard": {
    health: 1200,
    maxHealth: 1200,
    shield: 1200,
    maxShield: 1200,
    energy: 700,
    maxEnergy: 700,
    speed: 120,
    turnRate: 3,
    cargo: 280,
    tier: 3,
    faction: "lost-nova",
    weapons: [
      {
        id: "mgss-1",
        size: "medium",
        position: "front",
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "mgss Cannon",
            category: "mgss",
            tier: 3,
            baseStats: {
              damage: 70,
              range: 1100,
              accuracy: 0.88,
              rateOfFire: 5,
              energyCost: 10,
              cooldown: 3,
              effects: [{ type: "plasma", magnitude: 1.5, duration: 5 }],
            },
            visualAsset: "weapons/mgss/advanced",
            mountRequirements: {
              size: "medium",
              power: 25,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 70,
              range: 1100,
              accuracy: 0.88,
              rateOfFire: 5,
              energyCost: 10,
              cooldown: 3,
              effects: [{ type: "plasma", magnitude: 1.5, duration: 5 }],
            },
            effects: [{ type: "plasma", magnitude: 1.5, duration: 5 }],
          },
        },
      },
    ],
    defense: {
      armor: 400,
      shield: 1200,
      evasion: 0.3,
      regeneration: 10,
    },
    mobility: {
      speed: 120,
      turnRate: 3,
      acceleration: 60,
    },
    abilities: [
      {
        name: "Forbidden Technology",
        description: "Unleashes devastating area damage",
        cooldown: 50,
        duration: 15,
        active: false,
        effect: { type: "damage", magnitude: 2.5, duration: 15, radius: 500 },
      },
    ],
  },
  "ethereal-galleon": {
    health: 1300,
    maxHealth: 1300,
    shield: 1200,
    maxShield: 1200,
    energy: 800,
    maxEnergy: 800,
    speed: 100,
    turnRate: 3,
    cargo: 300,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "mgss-1",
        size: "medium",
        position: "front",
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "mgss Cannon",
            category: "mgss",
            tier: 3,
            baseStats: {
              damage: 80,
              range: 1200,
              accuracy: 0.9,
              rateOfFire: 5,
              energyCost: 12,
              cooldown: 3,
              effects: [{ type: "plasma", magnitude: 1.6, duration: 4 }],
            },
            visualAsset: "weapons/mgss/advanced",
            mountRequirements: {
              size: "medium",
              power: 30,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 80,
              range: 1200,
              accuracy: 0.9,
              rateOfFire: 5,
              energyCost: 12,
              cooldown: 3,
              effects: [{ type: "plasma", magnitude: 1.6, duration: 4 }],
            },
            effects: [{ type: "plasma", magnitude: 1.6, duration: 4 }],
          },
        },
      },
    ],
    defense: {
      armor: 400,
      shield: 1200,
      evasion: 0.3,
      regeneration: 10,
    },
    mobility: {
      speed: 100,
      turnRate: 3,
      acceleration: 50,
    },
    abilities: [
      {
        name: "Ancient Energy",
        description: "Temporarily increases damage output",
        cooldown: 40,
        duration: 12,
        active: false,
        effect: { type: "damage", magnitude: 2.2, duration: 12 },
      },
    ],
  },

  // Equator Horizon Ships
  "celestial-arbiter": {
    health: 1500,
    maxHealth: 1500,
    shield: 1000,
    maxShield: 1000,
    energy: 800,
    maxEnergy: 800,
    speed: 80,
    turnRate: 3,
    cargo: 300,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "rail-1",
        size: "large",
        position: "front",
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "heavy-railgun",
            name: "Heavy Railgun",
            category: "railGun",
            tier: 3,
            baseStats: {
              damage: 300,
              range: 1500,
              accuracy: 0.95,
              rateOfFire: 3,
              energyCost: 15,
              cooldown: 3,
              effects: [{ type: "gauss", damage: 100, duration: 3, magnitude: 1.5 }],
            },
            visualAsset: "weapons/railgun/heavy",
            mountRequirements: {
              size: "large",
              power: 40,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 300,
              range: 1500,
              accuracy: 0.95,
              rateOfFire: 3,
              energyCost: 15,
              cooldown: 3,
              effects: [{ type: "gauss", damage: 100, duration: 3, magnitude: 1.5 }],
            },
            effects: [{ type: "gauss", damage: 100, duration: 3, magnitude: 1.5 }],
          },
        },
      },
    ],
    defense: {
      armor: 500,
      shield: 1000,
      evasion: 0.2,
      regeneration: 8,
    },
    mobility: {
      speed: 80,
      turnRate: 3,
      acceleration: 40,
    },
    abilities: [
      {
        name: "Balance Restoration",
        description: "Creates a powerful shield around nearby allies",
        cooldown: 45,
        duration: 15,
        active: false,
        effect: { type: "shield", magnitude: 2, duration: 15, radius: 500 },
      },
    ],
  },
  "stellar-equinox": {
    health: 1100,
    maxHealth: 1100,
    shield: 900,
    maxShield: 900,
    energy: 700,
    maxEnergy: 700,
    speed: 120,
    turnRate: 3,
    cargo: 250,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "gauss-1",
        size: "large",
        position: "front",
        rotation: 0,
        allowedCategories: ["gaussCannon"],
        currentWeapon: {
          config: {
            id: "gauss-cannon",
            name: "Gauss Cannon",
            category: "gaussCannon",
            tier: 3,
            baseStats: {
              damage: 200,
              range: 1300,
              accuracy: 0.93,
              rateOfFire: 4,
              energyCost: 15,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.6, duration: 3 }],
            },
            visualAsset: "weapons/gauss/heavy",
            mountRequirements: {
              size: "large",
              power: 35,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 200,
              range: 1300,
              accuracy: 0.93,
              rateOfFire: 4,
              energyCost: 15,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.6, duration: 3 }],
            },
            effects: [{ type: "gauss", magnitude: 1.6, duration: 3 }],
          },
        },
      },
    ],
    defense: {
      armor: 350,
      shield: 900,
      evasion: 0.35,
      regeneration: 8,
    },
    mobility: {
      speed: 120,
      turnRate: 3,
      acceleration: 60,
    },
    abilities: [
      {
        name: "Perfect Harmony",
        description: "Creates a protective shield around allies",
        cooldown: 35,
        duration: 10,
        active: false,
        effect: { type: "shield", magnitude: 1.8, duration: 10, radius: 400 },
      },
    ],
  },
  "chronos-sentinel": {
    health: 900,
    maxHealth: 900,
    shield: 1100,
    maxShield: 1100,
    energy: 600,
    maxEnergy: 600,
    speed: 140,
    turnRate: 3,
    cargo: 200,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "rail-1",
        size: "large",
        position: "front",
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "heavy-railgun",
            name: "Heavy Railgun",
            category: "railGun",
            tier: 3,
            baseStats: {
              damage: 250,
              range: 1400,
              accuracy: 0.92,
              rateOfFire: 3,
              energyCost: 18,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.7, duration: 2 }],
            },
            visualAsset: "weapons/railgun/heavy",
            mountRequirements: {
              size: "large",
              power: 40,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 250,
              range: 1400,
              accuracy: 0.92,
              rateOfFire: 3,
              energyCost: 18,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.7, duration: 2 }],
            },
            effects: [{ type: "gauss", magnitude: 1.7, duration: 2 }],
          },
        },
      },
    ],
    defense: {
      armor: 300,
      shield: 1100,
      evasion: 0.4,
      regeneration: 9,
    },
    mobility: {
      speed: 140,
      turnRate: 3,
      acceleration: 70,
    },
    abilities: [
      {
        name: "Time Dilation",
        description: "Creates a field that slows enemies",
        cooldown: 30,
        duration: 8,
        active: false,
        effect: { type: "speed", magnitude: 0.5, duration: 8, radius: 300 },
      },
    ],
  },
  "nebulas-judgement": {
    health: 1000,
    maxHealth: 1000,
    shield: 800,
    maxShield: 800,
    energy: 600,
    maxEnergy: 600,
    speed: 160,
    turnRate: 3,
    cargo: 220,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "mgss-1",
        size: "medium",
        position: "front",
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "mgss Cannon",
            category: "mgss",
            tier: 3,
            baseStats: {
              damage: 150,
              range: 1100,
              accuracy: 0.9,
              rateOfFire: 5,
              energyCost: 12,
              cooldown: 3,
              effects: [{ type: "plasma", magnitude: 1.4, duration: 3 }],
            },
            visualAsset: "weapons/mgss/advanced",
            mountRequirements: {
              size: "medium",
              power: 30,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 150,
              range: 1100,
              accuracy: 0.9,
              rateOfFire: 5,
              energyCost: 12,
              cooldown: 3,
              effects: [{ type: "plasma", magnitude: 1.4, duration: 3 }],
            },
            effects: [{ type: "plasma", magnitude: 1.4, duration: 3 }],
          },
        },
      },
    ],
    defense: {
      armor: 400,
      shield: 800,
      evasion: 0.45,
      regeneration: 7,
    },
    mobility: {
      speed: 160,
      turnRate: 3,
      acceleration: 80,
    },
    abilities: [
      {
        name: "Swift Justice",
        description: "Temporarily increases damage output",
        cooldown: 25,
        duration: 6,
        active: false,
        effect: { type: "damage", magnitude: 2, duration: 6 },
      },
    ],
  },
  "aetherial-horizon": {
    health: 1400,
    maxHealth: 1400,
    shield: 1300,
    maxShield: 1300,
    energy: 800,
    maxEnergy: 800,
    speed: 110,
    turnRate: 3,
    cargo: 300,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "rocket-1",
        size: "large",
        position: "front",
        rotation: 0,
        allowedCategories: ["rockets"],
        currentWeapon: {
          config: {
            id: "heavy-rockets",
            name: "Heavy Rockets",
            category: "rockets",
            tier: 3,
            baseStats: {
              damage: 280,
              range: 1600,
              accuracy: 0.85,
              rateOfFire: 2,
              energyCost: 20,
              cooldown: 4,
              effects: [{ type: "explosive", magnitude: 2.0, duration: 2, radius: 80 }],
            },
            visualAsset: "weapons/rockets/heavy",
            mountRequirements: {
              size: "large",
              power: 45,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 280,
              range: 1600,
              accuracy: 0.85,
              rateOfFire: 2,
              energyCost: 20,
              cooldown: 4,
              effects: [{ type: "explosive", magnitude: 2.0, duration: 2, radius: 80 }],
            },
            effects: [{ type: "explosive", magnitude: 2.0, duration: 2, radius: 80 }],
          },
        },
      },
    ],
    defense: {
      armor: 450,
      shield: 1300,
      evasion: 0.3,
      regeneration: 10,
    },
    mobility: {
      speed: 110,
      turnRate: 3,
      acceleration: 55,
    },
    abilities: [
      {
        name: "First Contact",
        description: "Creates a massive protective shield",
        cooldown: 55,
        duration: 18,
        active: false,
        effect: { type: "shield", magnitude: 2.5, duration: 18, radius: 600 },
      },
    ],
  },
  "cosmic-crusader": {
    health: 1200,
    maxHealth: 1200,
    shield: 1000,
    maxShield: 1000,
    energy: 700,
    maxEnergy: 700,
    speed: 130,
    turnRate: 3,
    cargo: 280,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "gauss-1",
        size: "large",
        position: "front",
        rotation: 0,
        allowedCategories: ["gaussCannon"],
        currentWeapon: {
          config: {
            id: "gauss-cannon",
            name: "Gauss Cannon",
            category: "gaussCannon",
            tier: 3,
            baseStats: {
              damage: 220,
              range: 1400,
              accuracy: 0.94,
              rateOfFire: 3,
              energyCost: 18,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.7, duration: 3 }],
            },
            visualAsset: "weapons/gauss/heavy",
            mountRequirements: {
              size: "large",
              power: 40,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 220,
              range: 1400,
              accuracy: 0.94,
              rateOfFire: 3,
              energyCost: 18,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.7, duration: 3 }],
            },
            effects: [{ type: "gauss", magnitude: 1.7, duration: 3 }],
          },
        },
      },
    ],
    defense: {
      armor: 380,
      shield: 1000,
      evasion: 0.35,
      regeneration: 9,
    },
    mobility: {
      speed: 130,
      turnRate: 3,
      acceleration: 65,
    },
    abilities: [
      {
        name: "Threat Neutralization",
        description: "Unleashes a devastating attack",
        cooldown: 42,
        duration: 12,
        active: false,
        effect: { type: "damage", magnitude: 2.3, duration: 12, radius: 450 },
      },
    ],
  },
  "balancekeepers-wrath": {
    health: 1600,
    maxHealth: 1600,
    shield: 1400,
    maxShield: 1400,
    energy: 900,
    maxEnergy: 900,
    speed: 70,
    turnRate: 3,
    cargo: 400,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "rail-1",
        size: "large",
        position: "front",
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "heavy-railgun",
            name: "Heavy Railgun",
            category: "railGun",
            tier: 3,
            baseStats: {
              damage: 350,
              range: 1800,
              accuracy: 0.96,
              rateOfFire: 2,
              energyCost: 25,
              cooldown: 4,
              effects: [{ type: "gauss", magnitude: 2.0, duration: 4 }],
            },
            visualAsset: "weapons/railgun/heavy",
            mountRequirements: {
              size: "large",
              power: 50,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 350,
              range: 1800,
              accuracy: 0.96,
              rateOfFire: 2,
              energyCost: 25,
              cooldown: 4,
              effects: [{ type: "gauss", magnitude: 2.0, duration: 4 }],
            },
            effects: [{ type: "gauss", magnitude: 2.0, duration: 4 }],
          },
        },
      },
    ],
    defense: {
      armor: 600,
      shield: 1400,
      evasion: 0.2,
      regeneration: 12,
    },
    mobility: {
      speed: 70,
      turnRate: 3,
      acceleration: 35,
    },
    abilities: [
      {
        name: "Wrath of Balance",
        description: "Unleashes devastating area damage",
        cooldown: 60,
        duration: 20,
        active: false,
        effect: { type: "damage", magnitude: 3.0, duration: 20, radius: 700 },
      },
    ],
  },
  "ecliptic-watcher": {
    health: 800,
    maxHealth: 800,
    shield: 1000,
    maxShield: 1000,
    energy: 600,
    maxEnergy: 600,
    speed: 180,
    turnRate: 3,
    cargo: 200,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "mgss-1",
        size: "medium",
        position: "front",
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "mgss Cannon",
            category: "mgss",
            tier: 3,
            baseStats: {
              damage: 100,
              range: 1000,
              accuracy: 0.92,
              rateOfFire: 6,
              energyCost: 10,
              cooldown: 3,
              effects: [{ type: "plasma", magnitude: 1.3, duration: 2 }],
            },
            visualAsset: "weapons/mgss/advanced",
            mountRequirements: {
              size: "medium",
              power: 25,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 100,
              range: 1000,
              accuracy: 0.92,
              rateOfFire: 6,
              energyCost: 10,
              cooldown: 3,
              effects: [{ type: "plasma", magnitude: 1.3, duration: 2 }],
            },
            effects: [{ type: "plasma", magnitude: 1.3, duration: 2 }],
          },
        },
      },
    ],
    defense: {
      armor: 250,
      shield: 1000,
      evasion: 0.5,
      regeneration: 8,
    },
    mobility: {
      speed: 180,
      turnRate: 3,
      acceleration: 90,
    },
    abilities: [
      {
        name: "Perfect Stealth",
        description: "Activates perfect stealth technology",
        cooldown: 38,
        duration: 10,
        active: false,
        effect: { type: "stealth", magnitude: 1.0, duration: 10 },
      },
    ],
  },
  "harmonys-vanguard": {
    health: 1300,
    maxHealth: 1300,
    shield: 1100,
    maxShield: 1100,
    energy: 800,
    maxEnergy: 800,
    speed: 140,
    turnRate: 3,
    cargo: 300,
    tier: 3,
    faction: "equator-horizon",
    weapons: [
      {
        id: "gauss-1",
        size: "large",
        position: "front",
        rotation: 0,
        allowedCategories: ["gaussCannon"],
        currentWeapon: {
          config: {
            id: "gauss-cannon",
            name: "Gauss Cannon",
            category: "gaussCannon",
            tier: 3,
            baseStats: {
              damage: 240,
              range: 1500,
              accuracy: 0.93,
              rateOfFire: 3,
              energyCost: 20,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.8, duration: 3 }],
            },
            visualAsset: "weapons/gauss/heavy",
            mountRequirements: {
              size: "large",
              power: 45,
            },
          },
          state: {
            status: "ready",
            currentStats: {
              damage: 240,
              range: 1500,
              accuracy: 0.93,
              rateOfFire: 3,
              energyCost: 20,
              cooldown: 3,
              effects: [{ type: "gauss", magnitude: 1.8, duration: 3 }],
            },
            effects: [{ type: "gauss", magnitude: 1.8, duration: 3 }],
          },
        },
      },
    ],
    defense: {
      armor: 420,
      shield: 1100,
      evasion: 0.35,
      regeneration: 10,
    },
    mobility: {
      speed: 140,
      turnRate: 3,
      acceleration: 70,
    },
    abilities: [
      {
        name: "Order from Chaos",
        description: "Creates a powerful shield field",
        cooldown: 48,
        duration: 15,
        active: false,
        effect: { type: "shield", magnitude: 2.2, duration: 15, radius: 550 },
      },
    ],
  },
} as const;

// Helper function to get ship stats with type safety
export function getShipStats(shipClass: FactionShipClass): FactionShipStats {
  return SHIP_STATS[shipClass];
}

// Helper function to calculate display stats
export function getShipDisplayStats(stats: FactionShipStats): CommonShipDisplayStats {
  return {
    weapons: {
      damage: stats.weapons.reduce((sum: number, w: WeaponMount) => 
        sum + (w.currentWeapon?.state.currentStats.damage || 0), 0),
      range: Math.max(...stats.weapons.map((w: WeaponMount) => 
        w.currentWeapon?.state.currentStats.range || 0)),
      accuracy: stats.weapons.reduce((sum: number, w: WeaponMount) => 
        sum + (w.currentWeapon?.state.currentStats.accuracy || 0), 0) / 
        (stats.weapons.filter(w => w.currentWeapon).length || 1),
    },
    defense: {
      hull: stats.health,
      shield: stats.shield,
      armor: stats.defense.armor,
    },
    mobility: {
      speed: stats.speed,
      agility: stats.turnRate * 20, // Convert turn rate to agility score
      jumpRange: 0, // Base ships don't have jump capability
    },
    systems: {
      power: Math.round(stats.weapons.length * 30 + stats.shield / 10),
      radar: Math.round(
        stats.weapons.reduce((sum: number, w: WeaponMount) => 
          sum + (w.currentWeapon?.state.currentStats.range || 0), 0) / 100,
      ),
      efficiency: Math.round(
        (1 - stats.weapons.reduce((sum: number, w: WeaponMount) => 
          sum + (w.currentWeapon?.state.currentStats.cooldown || 0), 0) / 10) * 100,
      ),
    },
  };
}
