import {
  DAMAGE_BOOST_EFFECT,
  EXPLOSIVE_EFFECT,
  GAUSS_EFFECT,
  PLASMA_EFFECT,
  SPEED_BOOST_EFFECT,
  SPEED_REDUCTION_EFFECT,
  STEALTH_EFFECT,
} from '../../effects/types_effects/shipEffects';
import { FactionShipStats, SpaceRatsShipClass } from '../../types/ships/FactionShipTypes';
import {
  WeaponInstance,
  WeaponMountPosition,
  WeaponMountSize,
  WeaponStatus,
} from '../../types/weapons/WeaponTypes';

export const SPACE_RATS_SHIPS: Record<SpaceRatsShipClass, FactionShipStats> = {
  ratKing: {
    health: 1200,
    maxHealth: 1200,
    shield: 1000,
    maxShield: 1000,
    energy: 800,
    maxEnergy: 800,
    speed: 120,
    turnRate: 2.5,
    cargo: 400,
    tier: 3,
    faction: 'space-rats',
    weapons: [
      {
        id: 'mgss-1',
        size: 'large' as WeaponMountSize,
        position: 'turret' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['mgss'],
        currentWeapon: {
          config: {
            id: 'heavy-mgss',
            name: 'Heavy MGSS Cannon',
            category: 'mgss',
            tier: 3,
            baseStats: {
              damage: 200,
              range: 800,
              accuracy: 0.85,
              rateOfFire: 8,
              energyCost: 25,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: 'weapons/mgss/heavy',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 50,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 200,
              range: 800,
              accuracy: 0.85,
              rateOfFire: 8,
              energyCost: 25,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 400,
      shield: 1000,
      evasion: 0.3,
      regeneration: 10,
    },
    mobility: {
      speed: 120,
      turnRate: 2.5,
      acceleration: 60,
    },
    abilities: [
      {
        id: 'pirate-fury-ability',
        name: "Pirate's Fury",
        description: 'Increases damage and fire rate',
        cooldown: 45,
        duration: 10,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  asteroidMarauder: {
    health: 800,
    maxHealth: 800,
    shield: 600,
    maxShield: 600,
    energy: 500,
    maxEnergy: 500,
    speed: 180,
    turnRate: 4,
    cargo: 200,
    tier: 2,
    faction: 'space-rats',
    weapons: [
      {
        id: 'machine-gun-1',
        size: 'medium' as WeaponMountSize,
        position: 'turret' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['machineGun'],
        currentWeapon: {
          config: {
            id: 'rapid-machine-gun',
            name: 'Rapid Machine Gun',
            category: 'machineGun',
            tier: 2,
            baseStats: {
              damage: 40,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 12,
              energyCost: 8,
              cooldown: 1,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: 'weapons/machineGun/rapid',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 30,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 40,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 12,
              energyCost: 8,
              cooldown: 1,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 200,
      shield: 600,
      evasion: 0.5,
      regeneration: 6,
    },
    mobility: {
      speed: 180,
      turnRate: 4,
      acceleration: 90,
    },
    abilities: [
      {
        id: 'scavenger-boost-ability',
        name: 'Scavenger Boost',
        description: 'Temporarily increases speed and evasion',
        cooldown: 20,
        duration: 6,
        active: false,
        effect: SPEED_BOOST_EFFECT,
      },
    ],
  },
  rogueNebula: {
    health: 700,
    maxHealth: 700,
    shield: 800,
    maxShield: 800,
    energy: 700,
    maxEnergy: 700,
    speed: 150,
    turnRate: 3,
    cargo: 250,
    tier: 2,
    faction: 'space-rats',
    weapons: [
      {
        id: 'rail-1',
        size: 'medium' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['railGun'],
        currentWeapon: {
          config: {
            id: 'advanced-railgun',
            name: 'Advanced Railgun',
            category: 'railGun',
            tier: 2,
            baseStats: {
              damage: 150,
              range: 1000,
              accuracy: 0.9,
              rateOfFire: 3,
              energyCost: 20,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: 'weapons/railgun/advanced',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 40,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 150,
              range: 1000,
              accuracy: 0.9,
              rateOfFire: 3,
              energyCost: 20,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 150,
      shield: 800,
      evasion: 0.4,
      regeneration: 8,
    },
    mobility: {
      speed: 150,
      turnRate: 3,
      acceleration: 75,
    },
    abilities: [
      {
        id: 'stealth-drive-ability',
        name: 'Stealth Drive',
        description: 'Activates cloaking technology',
        cooldown: 30,
        duration: 8,
        active: false,
        effect: STEALTH_EFFECT,
      },
    ],
  },
  ratsRevenge: {
    health: 900,
    maxHealth: 900,
    shield: 900,
    maxShield: 900,
    energy: 600,
    maxEnergy: 600,
    speed: 140,
    turnRate: 2.8,
    cargo: 300,
    tier: 2,
    faction: 'space-rats',
    weapons: [
      {
        id: 'rockets-1',
        size: 'medium' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['rockets'],
        currentWeapon: {
          config: {
            id: 'scombatm-rockets',
            name: 'Scombatm Rockets',
            category: 'rockets',
            tier: 2,
            baseStats: {
              damage: 120,
              range: 800,
              accuracy: 0.75,
              rateOfFire: 4,
              energyCost: 15,
              cooldown: 4,
              effects: [EXPLOSIVE_EFFECT],
            },
            visualAsset: 'weapons/rockets/scombatm',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 35,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 120,
              range: 800,
              accuracy: 0.75,
              rateOfFire: 4,
              energyCost: 15,
              cooldown: 4,
              effects: [EXPLOSIVE_EFFECT],
            },
            effects: [EXPLOSIVE_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 300,
      shield: 900,
      evasion: 0.35,
      regeneration: 9,
    },
    mobility: {
      speed: 140,
      turnRate: 2.8,
      acceleration: 70,
    },
    abilities: [
      {
        id: 'vengeance-strike-ability',
        name: 'Vengeance Strike',
        description: 'Increases damage when health is low',
        cooldown: 40,
        duration: 12,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  darkSectorCorsair: {
    health: 1000,
    maxHealth: 1000,
    shield: 1200,
    maxShield: 1200,
    energy: 900,
    maxEnergy: 900,
    speed: 130,
    turnRate: 2.5,
    cargo: 350,
    tier: 3,
    faction: 'space-rats',
    weapons: [
      {
        id: 'mgss-2',
        size: 'large' as WeaponMountSize,
        position: 'turret' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['mgss'],
        currentWeapon: {
          config: {
            id: 'advanced-mgss',
            name: 'Advanced MGSS Cannon',
            category: 'mgss',
            tier: 3,
            baseStats: {
              damage: 180,
              range: 900,
              accuracy: 0.88,
              rateOfFire: 6,
              energyCost: 20,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: 'weapons/mgss/advanced',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 45,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 180,
              range: 900,
              accuracy: 0.88,
              rateOfFire: 6,
              energyCost: 20,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 350,
      shield: 1200,
      evasion: 0.3,
      regeneration: 12,
    },
    mobility: {
      speed: 130,
      turnRate: 2.5,
      acceleration: 65,
    },
    abilities: [
      {
        id: 'sector-control-ability',
        name: 'Sector Control',
        description: 'Creates a field that slows enemies',
        cooldown: 35,
        duration: 8,
        active: false,
        effect: SPEED_REDUCTION_EFFECT,
      },
    ],
  },
  wailingWreck: {
    health: 900,
    maxHealth: 900,
    shield: 200,
    maxShield: 200,
    energy: 500,
    maxEnergy: 500,
    speed: 80,
    turnRate: 2,
    cargo: 180,
    tier: 2,
    faction: 'space-rats',
    weapons: [
      {
        id: 'rocket-1',
        size: 'large' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['rockets'],
        currentWeapon: {
          config: {
            id: 'heavy-rockets',
            name: 'Heavy Rockets',
            category: 'rockets',
            tier: 2,
            baseStats: {
              damage: 150,
              range: 1000,
              accuracy: 0.7,
              rateOfFire: 2,
              energyCost: 12,
              cooldown: 4,
              effects: [EXPLOSIVE_EFFECT],
            },
            visualAsset: 'weapons/rockets/heavy',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 35,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 150,
              range: 1000,
              accuracy: 0.7,
              rateOfFire: 2,
              energyCost: 12,
              cooldown: 4,
              effects: [EXPLOSIVE_EFFECT],
            },
            effects: [EXPLOSIVE_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 400,
      shield: 200,
      evasion: 0.2,
      regeneration: 2,
    },
    mobility: {
      speed: 80,
      turnRate: 2,
      acceleration: 40,
    },
    abilities: [
      {
        id: 'sonic-disruption-ability',
        name: 'Sonic Disruption',
        description: 'Slows down nearby enemies',
        cooldown: 35,
        duration: 8,
        active: false,
        effect: SPEED_REDUCTION_EFFECT,
      },
    ],
  },
  galacticScourge: {
    health: 1200,
    maxHealth: 1200,
    shield: 600,
    maxShield: 600,
    energy: 700,
    maxEnergy: 700,
    speed: 90,
    turnRate: 3,
    cargo: 250,
    tier: 3,
    faction: 'space-rats',
    weapons: [
      {
        id: 'rail-1',
        size: 'large' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['railGun'],
        currentWeapon: {
          config: {
            id: 'heavy-railgun',
            name: 'Heavy Railgun',
            category: 'railGun',
            tier: 3,
            baseStats: {
              damage: 200,
              range: 1100,
              accuracy: 0.85,
              rateOfFire: 3,
              energyCost: 15,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: 'weapons/railgun/heavy',
            mountRequirements: {
              size: 'large' as WeaponMountSize,
              power: 35,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 200,
              range: 1100,
              accuracy: 0.85,
              rateOfFire: 3,
              energyCost: 15,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 350,
      shield: 600,
      evasion: 0.3,
      regeneration: 5,
    },
    mobility: {
      speed: 90,
      turnRate: 3,
      acceleration: 45,
    },
    abilities: [
      {
        id: 'chaos-wave-ability',
        name: 'Chaos Wave',
        description: 'Unleashes a devastating wave of energy',
        cooldown: 40,
        duration: 12,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  plasmaFang: {
    health: 450,
    maxHealth: 450,
    shield: 300,
    maxShield: 300,
    energy: 400,
    maxEnergy: 400,
    speed: 160,
    turnRate: 3,
    cargo: 150,
    tier: 2,
    faction: 'space-rats',
    weapons: [
      {
        id: 'mgss-1',
        size: 'medium' as WeaponMountSize,
        position: 'turret' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['mgss'],
        currentWeapon: {
          config: {
            id: 'mgss-cannon',
            name: 'MGSS Cannon',
            category: 'mgss',
            tier: 2,
            baseStats: {
              damage: 35,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: 'weapons/mgss/basic',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 20,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 35,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 150,
      shield: 300,
      evasion: 0.5,
      regeneration: 4,
    },
    mobility: {
      speed: 160,
      turnRate: 3,
      acceleration: 80,
    },
    abilities: [
      {
        id: 'plasma-burst-ability',
        name: 'Plasma Burst',
        description: 'Releases a concentrated burst of plasma energy',
        cooldown: 22,
        duration: 6,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  verminVanguard: {
    health: 700,
    maxHealth: 700,
    shield: 450,
    maxShield: 450,
    energy: 400,
    maxEnergy: 400,
    speed: 110,
    turnRate: 3,
    cargo: 200,
    tier: 2,
    faction: 'space-rats',
    weapons: [
      {
        id: 'gauss-1',
        size: 'medium' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['gaussCannon'],
        currentWeapon: {
          config: {
            id: 'gauss-cannon',
            name: 'Gauss Cannon',
            category: 'gaussCannon',
            tier: 2,
            baseStats: {
              damage: 100,
              range: 950,
              accuracy: 0.88,
              rateOfFire: 2,
              energyCost: 25,
              cooldown: 2,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: 'weapons/gauss/basic',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 30,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 100,
              range: 950,
              accuracy: 0.88,
              rateOfFire: 2,
              energyCost: 25,
              cooldown: 2,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 250,
      shield: 450,
      evasion: 0.3,
      regeneration: 5,
    },
    mobility: {
      speed: 110,
      turnRate: 3,
      acceleration: 55,
    },
    abilities: [
      {
        id: 'rally-vermin-ability',
        name: 'Rally Vermin',
        description: 'Increases speed of nearby allies',
        cooldown: 28,
        duration: 10,
        active: false,
        effect: SPEED_BOOST_EFFECT,
      },
    ],
  },
  blackVoidBuccaneer: {
    health: 600,
    maxHealth: 600,
    shield: 500,
    maxShield: 500,
    energy: 450,
    maxEnergy: 450,
    speed: 135,
    turnRate: 3,
    cargo: 180,
    tier: 2,
    faction: 'space-rats',
    weapons: [
      {
        id: 'rail-1',
        size: 'medium' as WeaponMountSize,
        position: 'front' as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ['railGun'],
        currentWeapon: {
          config: {
            id: 'railgun',
            name: 'Railgun',
            category: 'railGun',
            tier: 2,
            baseStats: {
              damage: 140,
              range: 1000,
              accuracy: 0.9,
              rateOfFire: 3,
              energyCost: 12,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: 'weapons/railgun/basic',
            mountRequirements: {
              size: 'medium' as WeaponMountSize,
              power: 30,
            },
          },
          state: {
            status: 'ready' as WeaponStatus,
            currentStats: {
              damage: 140,
              range: 1000,
              accuracy: 0.9,
              rateOfFire: 3,
              energyCost: 12,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 200,
      shield: 500,
      evasion: 0.4,
      regeneration: 4,
    },
    mobility: {
      speed: 135,
      turnRate: 3,
      acceleration: 65,
    },
    abilities: [
      {
        id: 'void-cloak-ability',
        name: 'Void Cloak',
        description: 'Activates stealth capabilities',
        cooldown: 32,
        duration: 7,
        active: false,
        effect: STEALTH_EFFECT,
      },
    ],
  },
} as const;
