import { SpaceRatsShipClass, FactionShipStats } from "../../types/ships/FactionShipTypes";
import { WeaponMount, WeaponMountSize, WeaponMountPosition, WeaponStatus, WeaponInstance } from "../../types/weapons/WeaponTypes";
import {
  PLASMA_EFFECT,
  GAUSS_EFFECT,
  EXPLOSIVE_EFFECT,
  DAMAGE_BOOST_EFFECT,
  SPEED_BOOST_EFFECT,
  STEALTH_EFFECT,
  SPEED_REDUCTION_EFFECT,
} from "../../effects/types_effects/shipEffects";

export const SPACE_RATS_SHIPS: Record<SpaceRatsShipClass, FactionShipStats> = {
  ratKing: {
    health: 1000,
    maxHealth: 1000,
    shield: 500,
    maxShield: 500,
    energy: 500,
    maxEnergy: 500,
    speed: 100,
    turnRate: 2,
    cargo: 200,
    tier: 3,
    faction: "space-rats",
    weapons: [
      {
        id: "mgss-1",
        size: "medium" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "MGSS Cannon",
            category: "mgss",
            tier: 2,
            baseStats: {
              damage: 35,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 0.2,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: "weapons/mgss/basic",
            mountRequirements: {
              size: "medium" as WeaponMountSize,
              power: 20,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 35,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 0.2,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 300,
      shield: 500,
      evasion: 0.3,
      regeneration: 5,
    },
    mobility: {
      speed: 100,
      turnRate: 2,
      acceleration: 50,
    },
    abilities: [
      {
        name: "Pirate's Fury",
        description: "Increases weapon damage for a short duration",
        cooldown: 30,
        duration: 10,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  asteroidMarauder: {
    health: 600,
    maxHealth: 600,
    shield: 300,
    maxShield: 300,
    energy: 400,
    maxEnergy: 400,
    speed: 120,
    turnRate: 3,
    cargo: 150,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "mg-1",
        size: "small" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["machineGun"],
        currentWeapon: {
          config: {
            id: "basic-mg",
            name: "Basic Machine Gun",
            category: "machineGun",
            tier: 1,
            baseStats: {
              damage: 30,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 2,
              cooldown: 0.2,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: "weapons/machinegun/basic",
            mountRequirements: {
              size: "small" as WeaponMountSize,
              power: 10,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 30,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 2,
              cooldown: 0.2,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 200,
      shield: 300,
      evasion: 0.4,
      regeneration: 3,
    },
    mobility: {
      speed: 120,
      turnRate: 3,
      acceleration: 60,
    },
    abilities: [
      {
        name: "Scavenger Boost",
        description: "Temporarily increases movement speed",
        cooldown: 15,
        duration: 5,
        active: false,
        effect: SPEED_BOOST_EFFECT,
      },
    ],
  },
  rogueNebula: {
    health: 500,
    maxHealth: 500,
    shield: 400,
    maxShield: 400,
    energy: 450,
    maxEnergy: 450,
    speed: 150,
    turnRate: 3.5,
    cargo: 150,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "railgun-1",
        size: "medium" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "advanced-railgun",
            name: "Advanced Railgun",
            category: "railGun",
            tier: 2,
            baseStats: {
              damage: 200,
              range: 1100,
              accuracy: 0.85,
              rateOfFire: 5,
              energyCost: 8,
              cooldown: 0.3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: "weapons/railgun/advanced",
            mountRequirements: {
              size: "medium" as WeaponMountSize,
              power: 25,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 200,
              range: 1100,
              accuracy: 0.85,
              rateOfFire: 5,
              energyCost: 8,
              cooldown: 0.3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 150,
      shield: 400,
      evasion: 0.4,
      regeneration: 4,
    },
    mobility: {
      speed: 150,
      turnRate: 3.5,
      acceleration: 65,
    },
    abilities: [
      {
        name: "Stealth Drive",
        description: "Temporarily becomes stealthier",
        cooldown: 25,
        duration: 8,
        active: false,
        effect: STEALTH_EFFECT,
      },
    ],
  },
  ratsRevenge: {
    health: 800,
    maxHealth: 800,
    shield: 400,
    maxShield: 400,
    energy: 400,
    maxEnergy: 400,
    speed: 130,
    turnRate: 3,
    cargo: 200,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "mgss-1",
        size: "medium" as WeaponMountSize,
        position: "turret" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "MGSS Cannon",
            category: "mgss",
            tier: 2,
            baseStats: {
              damage: 40,
              range: 700,
              accuracy: 0.75,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: "weapons/mgss/basic",
            mountRequirements: {
              size: "medium" as WeaponMountSize,
              power: 20,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 40,
              range: 700,
              accuracy: 0.75,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 250,
      shield: 400,
      evasion: 0.3,
      regeneration: 5,
    },
    mobility: {
      speed: 130,
      turnRate: 3,
      acceleration: 65,
    },
    abilities: [
      {
        name: "Vengeful Strike",
        description: "Increases damage output temporarily",
        cooldown: 20,
        duration: 5,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  darkSectorCorsair: {
    health: 550,
    maxHealth: 550,
    shield: 350,
    maxShield: 350,
    energy: 400,
    maxEnergy: 400,
    speed: 140,
    turnRate: 3,
    cargo: 150,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "gauss-1",
        size: "medium" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["gaussCannon"],
        currentWeapon: {
          config: {
            id: "gauss-cannon",
            name: "Gauss Cannon",
            category: "gaussCannon",
            tier: 2,
            baseStats: {
              damage: 90,
              range: 850,
              accuracy: 0.9,
              rateOfFire: 5,
              energyCost: 8,
              cooldown: 2,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: "weapons/gauss/basic",
            mountRequirements: {
              size: "medium" as WeaponMountSize,
              power: 25,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 90,
              range: 850,
              accuracy: 0.9,
              rateOfFire: 5,
              energyCost: 8,
              cooldown: 2,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 180,
      shield: 350,
      evasion: 0.4,
      regeneration: 3,
    },
    mobility: {
      speed: 140,
      turnRate: 3,
      acceleration: 60,
    },
    abilities: [
      {
        name: "Shadow Strike",
        description: "Temporarily becomes harder to detect",
        cooldown: 18,
        duration: 4,
        active: false,
        effect: STEALTH_EFFECT,
      },
    ],
  },
  wailingWreck: {
    health: 900,
    maxHealth: 900,
    shield: 200,
    maxShield: 200,
    energy: 500,
    maxEnergy: 500,
    speed: 80,
    turnRate: 2,
    cargo: 180,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "rocket-1",
        size: "large" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["rockets"],
        currentWeapon: {
          config: {
            id: "heavy-rockets",
            name: "Heavy Rockets",
            category: "rockets",
            tier: 2,
            baseStats: {
              damage: 150,
              range: 1000,
              accuracy: 0.7,
              rateOfFire: 2,
              energyCost: 12,
              cooldown: 4,
              effects: [EXPLOSIVE_EFFECT],
            },
            visualAsset: "weapons/rockets/heavy",
            mountRequirements: {
              size: "large" as WeaponMountSize,
              power: 35,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 150,
              range: 1000,
              accuracy: 0.7,
              rateOfFire: 2,
              energyCost: 12,
              cooldown: 4,
              effects: [EXPLOSIVE_EFFECT],
            },
            effects: [EXPLOSIVE_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 400,
      shield: 200,
      evasion: 0.2,
      regeneration: 2,
    },
    mobility: {
      speed: 80,
      turnRate: 2,
      acceleration: 40,
    },
    abilities: [
      {
        name: "Sonic Disruption",
        description: "Slows down nearby enemies",
        cooldown: 35,
        duration: 8,
        active: false,
        effect: SPEED_REDUCTION_EFFECT,
      },
    ],
  },
  galacticScourge: {
    health: 1200,
    maxHealth: 1200,
    shield: 600,
    maxShield: 600,
    energy: 700,
    maxEnergy: 700,
    speed: 90,
    turnRate: 3,
    cargo: 250,
    tier: 3,
    faction: "space-rats",
    weapons: [
      {
        id: "rail-1",
        size: "large" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "heavy-railgun",
            name: "Heavy Railgun",
            category: "railGun",
            tier: 3,
            baseStats: {
              damage: 200,
              range: 1100,
              accuracy: 0.85,
              rateOfFire: 3,
              energyCost: 15,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: "weapons/railgun/heavy",
            mountRequirements: {
              size: "large" as WeaponMountSize,
              power: 35,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 200,
              range: 1100,
              accuracy: 0.85,
              rateOfFire: 3,
              energyCost: 15,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 350,
      shield: 600,
      evasion: 0.3,
      regeneration: 5,
    },
    mobility: {
      speed: 90,
      turnRate: 3,
      acceleration: 45,
    },
    abilities: [
      {
        name: "Chaos Wave",
        description: "Unleashes a devastating wave of energy",
        cooldown: 40,
        duration: 12,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  plasmaFang: {
    health: 450,
    maxHealth: 450,
    shield: 300,
    maxShield: 300,
    energy: 400,
    maxEnergy: 400,
    speed: 160,
    turnRate: 3,
    cargo: 150,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "mgss-1",
        size: "medium" as WeaponMountSize,
        position: "turret" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["mgss"],
        currentWeapon: {
          config: {
            id: "mgss-cannon",
            name: "MGSS Cannon",
            category: "mgss",
            tier: 2,
            baseStats: {
              damage: 35,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            visualAsset: "weapons/mgss/basic",
            mountRequirements: {
              size: "medium" as WeaponMountSize,
              power: 20,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 35,
              range: 600,
              accuracy: 0.8,
              rateOfFire: 8,
              energyCost: 5,
              cooldown: 2,
              effects: [PLASMA_EFFECT],
            },
            effects: [PLASMA_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 150,
      shield: 300,
      evasion: 0.5,
      regeneration: 4,
    },
    mobility: {
      speed: 160,
      turnRate: 3,
      acceleration: 80,
    },
    abilities: [
      {
        name: "Plasma Burst",
        description: "Releases a concentrated burst of plasma energy",
        cooldown: 22,
        duration: 6,
        active: false,
        effect: DAMAGE_BOOST_EFFECT,
      },
    ],
  },
  verminVanguard: {
    health: 700,
    maxHealth: 700,
    shield: 450,
    maxShield: 450,
    energy: 400,
    maxEnergy: 400,
    speed: 110,
    turnRate: 3,
    cargo: 200,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "gauss-1",
        size: "medium" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["gaussCannon"],
        currentWeapon: {
          config: {
            id: "gauss-cannon",
            name: "Gauss Cannon",
            category: "gaussCannon",
            tier: 2,
            baseStats: {
              damage: 100,
              range: 950,
              accuracy: 0.88,
              rateOfFire: 2,
              energyCost: 25,
              cooldown: 2,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: "weapons/gauss/basic",
            mountRequirements: {
              size: "medium" as WeaponMountSize,
              power: 30,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 100,
              range: 950,
              accuracy: 0.88,
              rateOfFire: 2,
              energyCost: 25,
              cooldown: 2,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 250,
      shield: 450,
      evasion: 0.3,
      regeneration: 5,
    },
    mobility: {
      speed: 110,
      turnRate: 3,
      acceleration: 55,
    },
    abilities: [
      {
        name: "Rally Vermin",
        description: "Increases speed of nearby allies",
        cooldown: 28,
        duration: 10,
        active: false,
        effect: SPEED_BOOST_EFFECT,
      },
    ],
  },
  blackVoidBuccaneer: {
    health: 600,
    maxHealth: 600,
    shield: 500,
    maxShield: 500,
    energy: 450,
    maxEnergy: 450,
    speed: 135,
    turnRate: 3,
    cargo: 180,
    tier: 2,
    faction: "space-rats",
    weapons: [
      {
        id: "rail-1",
        size: "medium" as WeaponMountSize,
        position: "front" as WeaponMountPosition,
        rotation: 0,
        allowedCategories: ["railGun"],
        currentWeapon: {
          config: {
            id: "railgun",
            name: "Railgun",
            category: "railGun",
            tier: 2,
            baseStats: {
              damage: 140,
              range: 1000,
              accuracy: 0.9,
              rateOfFire: 3,
              energyCost: 12,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            visualAsset: "weapons/railgun/basic",
            mountRequirements: {
              size: "medium" as WeaponMountSize,
              power: 30,
            },
          },
          state: {
            status: "ready" as WeaponStatus,
            currentStats: {
              damage: 140,
              range: 1000,
              accuracy: 0.9,
              rateOfFire: 3,
              energyCost: 12,
              cooldown: 3,
              effects: [GAUSS_EFFECT],
            },
            effects: [GAUSS_EFFECT],
          },
        } as WeaponInstance,
      },
    ],
    defense: {
      armor: 200,
      shield: 500,
      evasion: 0.4,
      regeneration: 4,
    },
    mobility: {
      speed: 135,
      turnRate: 3,
      acceleration: 65,
    },
    abilities: [
      {
        name: "Void Cloak",
        description: "Activates stealth capabilities",
        cooldown: 32,
        duration: 7,
        active: false,
        effect: STEALTH_EFFECT,
      },
    ],
  },
} as const; 