export enum ExplorationEvents {
  SECTOR_EXPLORED = 'SECTOR_EXPLORED',
  SECTOR_ANALYZED = 'SECTOR_ANALYZED',
  DISCOVERY_MADE = 'DISCOVERY_MADE',
  DISCOVERY_ANALYZED = 'DISCOVERY_ANALYZED',
  RESOURCE_DISCOVERED = 'RESOURCE_DISCOVERED',
  VESSEL_DISPATCHED = 'VESSEL_DISPATCHED',
  VESSEL_ARRIVED = 'VESSEL_ARRIVED',
  VESSEL_STATUS_CHANGED = 'VESSEL_STATUS_CHANGED',
  ANALYSIS_STARTED = 'ANALYSIS_STARTED',
  ANALYSIS_COMPLETED = 'ANALYSIS_COMPLETED',
  ANALYSIS_FAILED = 'ANALYSIS_FAILED',
}
